// Generated by build-stimuli.mjs. Do not edit by hand.
const STIMULI = {
 "lists": {
  "1": [
   {
    "item": "def-01",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The kitchen has exactly one window.",
    "cand_A": "The window in the kitchen is open.",
    "cand_B": "A window in the kitchen is open."
   },
   {
    "item": "def-03",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The office has six lamps.",
    "cand_A": "The lamp in the office is broken.",
    "cand_B": "A lamp in the office is broken."
   },
   {
    "item": "def-05",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The garden has exactly one tree.",
    "cand_A": "The tree in the garden is dying.",
    "cand_B": "A tree in the garden is dying."
   },
   {
    "item": "def-07",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The hallway has six paintings.",
    "cand_A": "The painting in the hallway is crooked.",
    "cand_B": "A painting in the hallway is crooked."
   },
   {
    "item": "def-09",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The fridge has exactly one pear.",
    "cand_A": "The pear in the fridge is bruised.",
    "cand_B": "A pear in the fridge is bruised."
   },
   {
    "item": "def-11",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The car park has six vans.",
    "cand_A": "The van in the car park is dented.",
    "cand_B": "A van in the car park is dented."
   },
   {
    "item": "def-13",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The field has exactly one horse.",
    "cand_A": "The horse in the field is limping.",
    "cand_B": "A horse in the field is limping."
   },
   {
    "item": "def-15",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The shop has six tills.",
    "cand_A": "The till in the shop is jammed.",
    "cand_B": "A till in the shop is jammed."
   },
   {
    "item": "dual-02",
    "cls": "duality",
    "ctx": "Support",
    "context": "Tom has exactly two sisters.",
    "cand_A": "Both of his sisters are teachers.",
    "cand_B": "All of his sisters are teachers."
   },
   {
    "item": "dual-04",
    "cls": "duality",
    "ctx": "Control",
    "context": "Mark has three cars.",
    "cand_A": "Both of his cars are electric.",
    "cand_B": "All of his cars are electric."
   },
   {
    "item": "dual-06",
    "cls": "duality",
    "ctx": "Support",
    "context": "Omar has exactly two bikes.",
    "cand_A": "Both of his bikes were stolen.",
    "cand_B": "All of his bikes were stolen."
   },
   {
    "item": "dual-08",
    "cls": "duality",
    "ctx": "Control",
    "context": "Sam has three dogs.",
    "cand_A": "Both of his dogs are well trained.",
    "cand_B": "All of his dogs are well trained."
   },
   {
    "item": "dual-10",
    "cls": "duality",
    "ctx": "Support",
    "context": "Leo has exactly two flatmates.",
    "cand_A": "Both of his flatmates are students.",
    "cand_B": "All of his flatmates are students."
   },
   {
    "item": "dual-12",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ben has three guitars.",
    "cand_A": "Both of his guitars are out of tune.",
    "cand_B": "All of his guitars are out of tune."
   },
   {
    "item": "dual-14",
    "cls": "duality",
    "ctx": "Support",
    "context": "Jon has exactly two laptops.",
    "cand_A": "Both of his laptops are broken.",
    "cand_B": "All of his laptops are broken."
   },
   {
    "item": "add-01",
    "cls": "additive",
    "ctx": "Support",
    "context": "John came to the party.",
    "cand_A": "Bill came to the party too.",
    "cand_B": "Bill came to the party."
   },
   {
    "item": "add-03",
    "cls": "additive",
    "ctx": "Control",
    "context": "Priya didn't pass the exam.",
    "cand_A": "Marcus passed the exam too.",
    "cand_B": "Marcus passed the exam."
   },
   {
    "item": "add-05",
    "cls": "additive",
    "ctx": "Support",
    "context": "Paul quit the choir.",
    "cand_A": "Sara quit the choir too.",
    "cand_B": "Sara quit the choir."
   },
   {
    "item": "add-07",
    "cls": "additive",
    "ctx": "Control",
    "context": "Raj didn't read the report.",
    "cand_A": "Emma read the report too.",
    "cand_B": "Emma read the report."
   },
   {
    "item": "add-09",
    "cls": "additive",
    "ctx": "Support",
    "context": "Omar caught the early train.",
    "cand_A": "Lucy caught the early train too.",
    "cand_B": "Lucy caught the early train."
   },
   {
    "item": "add-11",
    "cls": "additive",
    "ctx": "Control",
    "context": "Tariq didn't fail the driving test.",
    "cand_A": "Holly failed the driving test too.",
    "cand_B": "Holly failed the driving test."
   },
   {
    "item": "add-13",
    "cls": "additive",
    "ctx": "Support",
    "context": "Elif visited the museum.",
    "cand_A": "Sam visited the museum too.",
    "cand_B": "Sam visited the museum."
   },
   {
    "item": "add-15",
    "cls": "additive",
    "ctx": "Control",
    "context": "Zoe didn't finish the marathon.",
    "cand_A": "Ian finished the marathon too.",
    "cand_B": "Ian finished the marathon."
   },
   {
    "item": "it-02",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Marco had never climbed the tower.",
    "cand_A": "He climbed the tower again today.",
    "cand_B": "He climbed the tower today."
   },
   {
    "item": "it-04",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Pete ran ten miles yesterday.",
    "cand_A": "He ran ten miles again today.",
    "cand_B": "He ran ten miles today."
   },
   {
    "item": "it-06",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Tom had never missed the bus.",
    "cand_A": "He missed the bus again today.",
    "cand_B": "He missed the bus today."
   },
   {
    "item": "it-08",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Rhys lost his keys yesterday.",
    "cand_A": "He lost his keys again today.",
    "cand_B": "He lost his keys today."
   },
   {
    "item": "it-10",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Adam had never burned the toast.",
    "cand_A": "He burned the toast again today.",
    "cand_B": "He burned the toast today."
   },
   {
    "item": "it-12",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Joel forgot his password yesterday.",
    "cand_A": "He forgot his password again today.",
    "cand_B": "He forgot his password today."
   },
   {
    "item": "it-14",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Kofi had never broken a plate.",
    "cand_A": "He broke a plate again today.",
    "cand_B": "He broke a plate today."
   },
   {
    "item": "fact-01",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The meeting was cancelled.",
    "cand_A": "Sam knows that the meeting was cancelled.",
    "cand_B": "Sam believes that the meeting was cancelled."
   },
   {
    "item": "fact-03",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The storm has not passed, though a rumour says otherwise.",
    "cand_A": "Ali knows that the storm has passed.",
    "cand_B": "Ali believes that the storm has passed."
   },
   {
    "item": "fact-05",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The train was delayed.",
    "cand_A": "Carl knows that the train was delayed.",
    "cand_B": "Carl believes that the train was delayed."
   },
   {
    "item": "fact-07",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The bridge is not closed, though a rumour says otherwise.",
    "cand_A": "Eli knows that the bridge is closed.",
    "cand_B": "Eli believes that the bridge is closed."
   },
   {
    "item": "fact-09",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The boss is on holiday.",
    "cand_A": "Gus knows that the boss is on holiday.",
    "cand_B": "Gus believes that the boss is on holiday."
   },
   {
    "item": "fact-11",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The flight was not cancelled, though a rumour says otherwise.",
    "cand_A": "Ivy knows that the flight was cancelled.",
    "cand_B": "Ivy believes that the flight was cancelled."
   },
   {
    "item": "fact-13",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The dog has been fed.",
    "cand_A": "Kim knows that the dog has been fed.",
    "cand_B": "Kim believes that the dog has been fed."
   },
   {
    "item": "fact-15",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The lift is not out of order, though a rumour says otherwise.",
    "cand_A": "Max knows that the lift is out of order.",
    "cand_B": "Max believes that the lift is out of order."
   },
   {
    "item": "cos-02",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Marta used to cycle to work.",
    "cand_A": "Marta stopped cycling to work.",
    "cand_B": "Marta doesn't cycle to work."
   },
   {
    "item": "cos-04",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Raj has never drunk coffee.",
    "cand_A": "Raj stopped drinking coffee.",
    "cand_B": "Raj doesn't drink coffee."
   },
   {
    "item": "cos-06",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Owen used to bite his nails.",
    "cand_A": "Owen stopped biting his nails.",
    "cand_B": "Owen doesn't bite his nails."
   },
   {
    "item": "cos-08",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Quinn has never run marathons.",
    "cand_A": "Quinn stopped running marathons.",
    "cand_B": "Quinn doesn't run marathons."
   },
   {
    "item": "cos-10",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Seb used to gamble.",
    "cand_A": "Seb stopped gambling.",
    "cand_B": "Seb doesn't gamble."
   },
   {
    "item": "cos-12",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Umar has never watched the news.",
    "cand_A": "Umar stopped watching the news.",
    "cand_B": "Umar doesn't watch the news."
   },
   {
    "item": "cos-14",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Will used to drive to work.",
    "cand_A": "Will stopped driving to work.",
    "cand_B": "Will doesn't drive to work."
   },
   {
    "item": "poss-01",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Judy has exactly one pie.",
    "cand_A": "Judy's pie won the contest.",
    "cand_B": "A pie of Judy's won the contest."
   },
   {
    "item": "poss-03",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Gerald has six photographs.",
    "cand_A": "Gerald's photograph hangs in the hall.",
    "cand_B": "A photograph of Gerald's hangs in the hall."
   },
   {
    "item": "poss-05",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Brian has exactly one bike.",
    "cand_A": "Brian's bike needs repairing.",
    "cand_B": "A bike of Brian's needs repairing."
   },
   {
    "item": "poss-07",
    "cls": "possessive",
    "ctx": "Control",
    "context": "David has six cars.",
    "cand_A": "David's car broke down yesterday.",
    "cand_B": "A car of David's broke down yesterday."
   },
   {
    "item": "poss-09",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Curtis has exactly one hat.",
    "cand_A": "Curtis's hat blew away.",
    "cand_B": "A hat of Curtis's blew away."
   },
   {
    "item": "poss-11",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Christopher has six skateboards.",
    "cand_A": "Christopher's skateboard was left outside.",
    "cand_B": "A skateboard of Christopher's was left outside."
   },
   {
    "item": "poss-13",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Leslie has exactly one print.",
    "cand_A": "Leslie's print faded badly.",
    "cand_B": "A print of Leslie's faded badly."
   },
   {
    "item": "poss-15",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Pamela has six snakes.",
    "cand_A": "Pamela's snake escaped last night.",
    "cand_B": "A snake of Pamela's escaped last night."
   },
   {
    "item": "cleft-02",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody made the phone call.",
    "cand_A": "It was Dan who made the phone call.",
    "cand_B": "Dan made the phone call."
   },
   {
    "item": "cleft-04",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone paid the bill.",
    "cand_A": "It was Douglas who paid the bill.",
    "cand_B": "Douglas paid the bill."
   },
   {
    "item": "cleft-06",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody opened the gate.",
    "cand_A": "It was George who opened the gate.",
    "cand_B": "George opened the gate."
   },
   {
    "item": "cleft-08",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone booked the room.",
    "cand_A": "It was Suzanne who booked the room.",
    "cand_B": "Suzanne booked the room."
   },
   {
    "item": "cleft-10",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody signed the form.",
    "cand_A": "It was Andrea who signed the form.",
    "cand_B": "Andrea signed the form."
   },
   {
    "item": "cleft-12",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone took the photograph.",
    "cand_A": "It was Nancy who took the photograph.",
    "cand_B": "Nancy took the photograph."
   },
   {
    "item": "cleft-14",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody answered the phone.",
    "cand_A": "It was Melinda who answered the phone.",
    "cand_B": "Melinda answered the phone."
   }
  ],
  "2": [
   {
    "item": "def-01",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The kitchen has four windows.",
    "cand_A": "The window in the kitchen is open.",
    "cand_B": "A window in the kitchen is open."
   },
   {
    "item": "def-03",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The office has exactly one lamp.",
    "cand_A": "The lamp in the office is broken.",
    "cand_B": "A lamp in the office is broken."
   },
   {
    "item": "def-05",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The garden has four trees.",
    "cand_A": "The tree in the garden is dying.",
    "cand_B": "A tree in the garden is dying."
   },
   {
    "item": "def-07",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The hallway has exactly one painting.",
    "cand_A": "The painting in the hallway is crooked.",
    "cand_B": "A painting in the hallway is crooked."
   },
   {
    "item": "def-09",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The fridge has four pears.",
    "cand_A": "The pear in the fridge is bruised.",
    "cand_B": "A pear in the fridge is bruised."
   },
   {
    "item": "def-11",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The car park has exactly one van.",
    "cand_A": "The van in the car park is dented.",
    "cand_B": "A van in the car park is dented."
   },
   {
    "item": "def-13",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The field has four horses.",
    "cand_A": "The horse in the field is limping.",
    "cand_B": "A horse in the field is limping."
   },
   {
    "item": "def-15",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The shop has exactly one till.",
    "cand_A": "The till in the shop is jammed.",
    "cand_B": "A till in the shop is jammed."
   },
   {
    "item": "dual-02",
    "cls": "duality",
    "ctx": "Control",
    "context": "Tom has five sisters.",
    "cand_A": "Both of his sisters are teachers.",
    "cand_B": "All of his sisters are teachers."
   },
   {
    "item": "dual-04",
    "cls": "duality",
    "ctx": "Support",
    "context": "Mark has exactly two cars.",
    "cand_A": "Both of his cars are electric.",
    "cand_B": "All of his cars are electric."
   },
   {
    "item": "dual-06",
    "cls": "duality",
    "ctx": "Control",
    "context": "Omar has five bikes.",
    "cand_A": "Both of his bikes were stolen.",
    "cand_B": "All of his bikes were stolen."
   },
   {
    "item": "dual-08",
    "cls": "duality",
    "ctx": "Support",
    "context": "Sam has exactly two dogs.",
    "cand_A": "Both of his dogs are well trained.",
    "cand_B": "All of his dogs are well trained."
   },
   {
    "item": "dual-10",
    "cls": "duality",
    "ctx": "Control",
    "context": "Leo has five flatmates.",
    "cand_A": "Both of his flatmates are students.",
    "cand_B": "All of his flatmates are students."
   },
   {
    "item": "dual-12",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ben has exactly two guitars.",
    "cand_A": "Both of his guitars are out of tune.",
    "cand_B": "All of his guitars are out of tune."
   },
   {
    "item": "dual-14",
    "cls": "duality",
    "ctx": "Control",
    "context": "Jon has five laptops.",
    "cand_A": "Both of his laptops are broken.",
    "cand_B": "All of his laptops are broken."
   },
   {
    "item": "add-01",
    "cls": "additive",
    "ctx": "Control",
    "context": "John didn't come to the party.",
    "cand_A": "Bill came to the party too.",
    "cand_B": "Bill came to the party."
   },
   {
    "item": "add-03",
    "cls": "additive",
    "ctx": "Support",
    "context": "Priya passed the exam.",
    "cand_A": "Marcus passed the exam too.",
    "cand_B": "Marcus passed the exam."
   },
   {
    "item": "add-05",
    "cls": "additive",
    "ctx": "Control",
    "context": "Paul didn't quit the choir.",
    "cand_A": "Sara quit the choir too.",
    "cand_B": "Sara quit the choir."
   },
   {
    "item": "add-07",
    "cls": "additive",
    "ctx": "Support",
    "context": "Raj read the report.",
    "cand_A": "Emma read the report too.",
    "cand_B": "Emma read the report."
   },
   {
    "item": "add-09",
    "cls": "additive",
    "ctx": "Control",
    "context": "Omar didn't catch the early train.",
    "cand_A": "Lucy caught the early train too.",
    "cand_B": "Lucy caught the early train."
   },
   {
    "item": "add-11",
    "cls": "additive",
    "ctx": "Support",
    "context": "Tariq failed the driving test.",
    "cand_A": "Holly failed the driving test too.",
    "cand_B": "Holly failed the driving test."
   },
   {
    "item": "add-13",
    "cls": "additive",
    "ctx": "Control",
    "context": "Elif didn't visit the museum.",
    "cand_A": "Sam visited the museum too.",
    "cand_B": "Sam visited the museum."
   },
   {
    "item": "add-15",
    "cls": "additive",
    "ctx": "Support",
    "context": "Zoe finished the marathon.",
    "cand_A": "Ian finished the marathon too.",
    "cand_B": "Ian finished the marathon."
   },
   {
    "item": "it-02",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Marco climbed the tower yesterday.",
    "cand_A": "He climbed the tower again today.",
    "cand_B": "He climbed the tower today."
   },
   {
    "item": "it-04",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Pete had never run ten miles.",
    "cand_A": "He ran ten miles again today.",
    "cand_B": "He ran ten miles today."
   },
   {
    "item": "it-06",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Tom missed the bus yesterday.",
    "cand_A": "He missed the bus again today.",
    "cand_B": "He missed the bus today."
   },
   {
    "item": "it-08",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Rhys had never lost his keys.",
    "cand_A": "He lost his keys again today.",
    "cand_B": "He lost his keys today."
   },
   {
    "item": "it-10",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Adam burned the toast yesterday.",
    "cand_A": "He burned the toast again today.",
    "cand_B": "He burned the toast today."
   },
   {
    "item": "it-12",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Joel had never forgotten his password.",
    "cand_A": "He forgot his password again today.",
    "cand_B": "He forgot his password today."
   },
   {
    "item": "it-14",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Kofi broke a plate yesterday.",
    "cand_A": "He broke a plate again today.",
    "cand_B": "He broke a plate today."
   },
   {
    "item": "fact-01",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The meeting was not cancelled, though a rumour says otherwise.",
    "cand_A": "Sam knows that the meeting was cancelled.",
    "cand_B": "Sam believes that the meeting was cancelled."
   },
   {
    "item": "fact-03",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The storm has passed.",
    "cand_A": "Ali knows that the storm has passed.",
    "cand_B": "Ali believes that the storm has passed."
   },
   {
    "item": "fact-05",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The train was not delayed, though a rumour says otherwise.",
    "cand_A": "Carl knows that the train was delayed.",
    "cand_B": "Carl believes that the train was delayed."
   },
   {
    "item": "fact-07",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The bridge is closed.",
    "cand_A": "Eli knows that the bridge is closed.",
    "cand_B": "Eli believes that the bridge is closed."
   },
   {
    "item": "fact-09",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The boss is not on holiday, though a rumour says otherwise.",
    "cand_A": "Gus knows that the boss is on holiday.",
    "cand_B": "Gus believes that the boss is on holiday."
   },
   {
    "item": "fact-11",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The flight was cancelled.",
    "cand_A": "Ivy knows that the flight was cancelled.",
    "cand_B": "Ivy believes that the flight was cancelled."
   },
   {
    "item": "fact-13",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The dog has not been fed, though a rumour says otherwise.",
    "cand_A": "Kim knows that the dog has been fed.",
    "cand_B": "Kim believes that the dog has been fed."
   },
   {
    "item": "fact-15",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The lift is out of order.",
    "cand_A": "Max knows that the lift is out of order.",
    "cand_B": "Max believes that the lift is out of order."
   },
   {
    "item": "cos-02",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Marta has never cycled to work.",
    "cand_A": "Marta stopped cycling to work.",
    "cand_B": "Marta doesn't cycle to work."
   },
   {
    "item": "cos-04",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Raj used to drink coffee.",
    "cand_A": "Raj stopped drinking coffee.",
    "cand_B": "Raj doesn't drink coffee."
   },
   {
    "item": "cos-06",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Owen has never bitten his nails.",
    "cand_A": "Owen stopped biting his nails.",
    "cand_B": "Owen doesn't bite his nails."
   },
   {
    "item": "cos-08",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Quinn used to run marathons.",
    "cand_A": "Quinn stopped running marathons.",
    "cand_B": "Quinn doesn't run marathons."
   },
   {
    "item": "cos-10",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Seb has never gambled.",
    "cand_A": "Seb stopped gambling.",
    "cand_B": "Seb doesn't gamble."
   },
   {
    "item": "cos-12",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Umar used to watch the news.",
    "cand_A": "Umar stopped watching the news.",
    "cand_B": "Umar doesn't watch the news."
   },
   {
    "item": "cos-14",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Will has never driven to work.",
    "cand_A": "Will stopped driving to work.",
    "cand_B": "Will doesn't drive to work."
   },
   {
    "item": "poss-01",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Judy has four pies.",
    "cand_A": "Judy's pie won the contest.",
    "cand_B": "A pie of Judy's won the contest."
   },
   {
    "item": "poss-03",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Gerald has exactly one photograph.",
    "cand_A": "Gerald's photograph hangs in the hall.",
    "cand_B": "A photograph of Gerald's hangs in the hall."
   },
   {
    "item": "poss-05",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Brian has four bikes.",
    "cand_A": "Brian's bike needs repairing.",
    "cand_B": "A bike of Brian's needs repairing."
   },
   {
    "item": "poss-07",
    "cls": "possessive",
    "ctx": "Support",
    "context": "David has exactly one car.",
    "cand_A": "David's car broke down yesterday.",
    "cand_B": "A car of David's broke down yesterday."
   },
   {
    "item": "poss-09",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Curtis has four hats.",
    "cand_A": "Curtis's hat blew away.",
    "cand_B": "A hat of Curtis's blew away."
   },
   {
    "item": "poss-11",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Christopher has exactly one skateboard.",
    "cand_A": "Christopher's skateboard was left outside.",
    "cand_B": "A skateboard of Christopher's was left outside."
   },
   {
    "item": "poss-13",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Leslie has four prints.",
    "cand_A": "Leslie's print faded badly.",
    "cand_B": "A print of Leslie's faded badly."
   },
   {
    "item": "poss-15",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Pamela has exactly one snake.",
    "cand_A": "Pamela's snake escaped last night.",
    "cand_B": "A snake of Pamela's escaped last night."
   },
   {
    "item": "cleft-02",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone made the phone call.",
    "cand_A": "It was Dan who made the phone call.",
    "cand_B": "Dan made the phone call."
   },
   {
    "item": "cleft-04",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody paid the bill.",
    "cand_A": "It was Douglas who paid the bill.",
    "cand_B": "Douglas paid the bill."
   },
   {
    "item": "cleft-06",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone opened the gate.",
    "cand_A": "It was George who opened the gate.",
    "cand_B": "George opened the gate."
   },
   {
    "item": "cleft-08",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody booked the room.",
    "cand_A": "It was Suzanne who booked the room.",
    "cand_B": "Suzanne booked the room."
   },
   {
    "item": "cleft-10",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone signed the form.",
    "cand_A": "It was Andrea who signed the form.",
    "cand_B": "Andrea signed the form."
   },
   {
    "item": "cleft-12",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody took the photograph.",
    "cand_A": "It was Nancy who took the photograph.",
    "cand_B": "Nancy took the photograph."
   },
   {
    "item": "cleft-14",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone answered the phone.",
    "cand_A": "It was Melinda who answered the phone.",
    "cand_B": "Melinda answered the phone."
   }
  ],
  "3": [
   {
    "item": "def-02",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The shelter has exactly one dog.",
    "cand_A": "The dog at the shelter is friendly.",
    "cand_B": "A dog at the shelter is friendly."
   },
   {
    "item": "def-04",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The garage has three cars.",
    "cand_A": "The car in the garage is red.",
    "cand_B": "A car in the garage is red."
   },
   {
    "item": "def-06",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The classroom has exactly one clock.",
    "cand_A": "The clock in the classroom is slow.",
    "cand_B": "A clock in the classroom is slow."
   },
   {
    "item": "def-08",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The bathroom has three towels.",
    "cand_A": "The towel in the bathroom is wet.",
    "cand_B": "A towel in the bathroom is wet."
   },
   {
    "item": "def-10",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The drawer has exactly one key.",
    "cand_A": "The key in the drawer is rusty.",
    "cand_B": "A key in the drawer is rusty."
   },
   {
    "item": "def-12",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The library has three computers.",
    "cand_A": "The computer in the library is frozen.",
    "cand_B": "A computer in the library is frozen."
   },
   {
    "item": "def-14",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The bedroom has exactly one mirror.",
    "cand_A": "The mirror in the bedroom is cracked.",
    "cand_B": "A mirror in the bedroom is cracked."
   },
   {
    "item": "dual-01",
    "cls": "duality",
    "ctx": "Support",
    "context": "Nina has exactly two brothers.",
    "cand_A": "Both of her brothers are doctors.",
    "cand_B": "All of her brothers are doctors."
   },
   {
    "item": "dual-03",
    "cls": "duality",
    "ctx": "Control",
    "context": "Priya has six cats.",
    "cand_A": "Both of her cats are asleep.",
    "cand_B": "All of her cats are asleep."
   },
   {
    "item": "dual-05",
    "cls": "duality",
    "ctx": "Support",
    "context": "Lena has exactly two children.",
    "cand_A": "Both of her children are at school.",
    "cand_B": "All of her children are at school."
   },
   {
    "item": "dual-07",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ruth has six plants.",
    "cand_A": "Both of her plants have died.",
    "cand_B": "All of her plants have died."
   },
   {
    "item": "dual-09",
    "cls": "duality",
    "ctx": "Support",
    "context": "Hana has exactly two sons.",
    "cand_A": "Both of her sons are engineers.",
    "cand_B": "All of her sons are engineers."
   },
   {
    "item": "dual-11",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ada has six daughters.",
    "cand_A": "Both of her daughters are married.",
    "cand_B": "All of her daughters are married."
   },
   {
    "item": "dual-13",
    "cls": "duality",
    "ctx": "Support",
    "context": "Iris has exactly two houses.",
    "cand_A": "Both of her houses are rented out.",
    "cand_B": "All of her houses are rented out."
   },
   {
    "item": "dual-15",
    "cls": "duality",
    "ctx": "Control",
    "context": "Mei has six suitcases.",
    "cand_A": "Both of her suitcases were lost.",
    "cand_B": "All of her suitcases were lost."
   },
   {
    "item": "add-02",
    "cls": "additive",
    "ctx": "Control",
    "context": "Lisa didn't see Dune.",
    "cand_A": "Donald saw Dune too.",
    "cand_B": "Donald saw Dune."
   },
   {
    "item": "add-04",
    "cls": "additive",
    "ctx": "Support",
    "context": "Anna won a prize.",
    "cand_A": "Kate won a prize too.",
    "cand_B": "Kate won a prize."
   },
   {
    "item": "add-06",
    "cls": "additive",
    "ctx": "Control",
    "context": "Mia didn't order the soup.",
    "cand_A": "Josh ordered the soup too.",
    "cand_B": "Josh ordered the soup."
   },
   {
    "item": "add-08",
    "cls": "additive",
    "ctx": "Support",
    "context": "Chloe voted for the proposal.",
    "cand_A": "Dan voted for the proposal too.",
    "cand_B": "Dan voted for the proposal."
   },
   {
    "item": "add-10",
    "cls": "additive",
    "ctx": "Control",
    "context": "Nora didn't sign the petition.",
    "cand_A": "Felix signed the petition too.",
    "cand_B": "Felix signed the petition."
   },
   {
    "item": "add-12",
    "cls": "additive",
    "ctx": "Support",
    "context": "Grace joined the gym.",
    "cand_A": "Owen joined the gym too.",
    "cand_B": "Owen joined the gym."
   },
   {
    "item": "add-14",
    "cls": "additive",
    "ctx": "Control",
    "context": "Hugo didn't buy a ticket.",
    "cand_A": "Amy bought a ticket too.",
    "cand_B": "Amy bought a ticket."
   },
   {
    "item": "it-01",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Jenna went ice skating yesterday.",
    "cand_A": "She went ice skating again today.",
    "cand_B": "She went ice skating today."
   },
   {
    "item": "it-03",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Aisha had never cooked a curry.",
    "cand_A": "She cooked a curry again today.",
    "cand_B": "She cooked a curry today."
   },
   {
    "item": "it-05",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Yuki visited Paris yesterday.",
    "cand_A": "She visited Paris again today.",
    "cand_B": "She visited Paris today."
   },
   {
    "item": "it-07",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Clara had never fallen off her bike.",
    "cand_A": "She fell off her bike again today.",
    "cand_B": "She fell off her bike today."
   },
   {
    "item": "it-09",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Lina baked bread yesterday.",
    "cand_A": "She baked bread again today.",
    "cand_B": "She baked bread today."
   },
   {
    "item": "it-11",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Fay had never been swimming.",
    "cand_A": "She went swimming again today.",
    "cand_B": "She went swimming today."
   },
   {
    "item": "it-13",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Maya sang in public yesterday.",
    "cand_A": "She sang in public again today.",
    "cand_B": "She sang in public today."
   },
   {
    "item": "it-15",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Noor had never ridden a horse.",
    "cand_A": "She rode a horse again today.",
    "cand_B": "She rode a horse today."
   },
   {
    "item": "fact-02",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The key is under the mat.",
    "cand_A": "Ruth knows that the key is under the mat.",
    "cand_B": "Ruth believes that the key is under the mat."
   },
   {
    "item": "fact-04",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The shop is not closed today, though a rumour says otherwise.",
    "cand_A": "Bea knows that the shop is closed today.",
    "cand_B": "Bea believes that the shop is closed today."
   },
   {
    "item": "fact-06",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The exam has been postponed.",
    "cand_A": "Dina knows that the exam has been postponed.",
    "cand_B": "Dina believes that the exam has been postponed."
   },
   {
    "item": "fact-08",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The concert did not sell out, though a rumour says otherwise.",
    "cand_A": "Fran knows that the concert sold out.",
    "cand_B": "Fran believes that the concert sold out."
   },
   {
    "item": "fact-10",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The milk has gone off.",
    "cand_A": "Hal knows that the milk has gone off.",
    "cand_B": "Hal believes that the milk has gone off."
   },
   {
    "item": "fact-12",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The printer is not broken, though a rumour says otherwise.",
    "cand_A": "Jay knows that the printer is broken.",
    "cand_B": "Jay believes that the printer is broken."
   },
   {
    "item": "fact-14",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The tickets are free.",
    "cand_A": "Lou knows that the tickets are free.",
    "cand_B": "Lou believes that the tickets are free."
   },
   {
    "item": "cos-01",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Scott used to smoke.",
    "cand_A": "Scott stopped smoking.",
    "cand_B": "Scott doesn't smoke."
   },
   {
    "item": "cos-03",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Iris has never played the piano.",
    "cand_A": "Iris stopped playing the piano.",
    "cand_B": "Iris doesn't play the piano."
   },
   {
    "item": "cos-05",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Nell used to eat meat.",
    "cand_A": "Nell stopped eating meat.",
    "cand_B": "Nell doesn't eat meat."
   },
   {
    "item": "cos-07",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Pia has never gone to church.",
    "cand_A": "Pia stopped going to church.",
    "cand_B": "Pia doesn't go to church."
   },
   {
    "item": "cos-09",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Rosa used to write poetry.",
    "cand_A": "Rosa stopped writing poetry.",
    "cand_B": "Rosa doesn't write poetry."
   },
   {
    "item": "cos-11",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Tess has never sung in a choir.",
    "cand_A": "Tess stopped singing in a choir.",
    "cand_B": "Tess doesn't sing in a choir."
   },
   {
    "item": "cos-13",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Vera used to wear glasses.",
    "cand_A": "Vera stopped wearing glasses.",
    "cand_B": "Vera doesn't wear glasses."
   },
   {
    "item": "cos-15",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Xavi has never taken the bus.",
    "cand_A": "Xavi stopped taking the bus.",
    "cand_B": "Xavi doesn't take the bus."
   },
   {
    "item": "poss-02",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Deanna has five ladders.",
    "cand_A": "Deanna's ladder was stolen.",
    "cand_B": "A ladder of Deanna's was stolen."
   },
   {
    "item": "poss-04",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Anne has exactly one vase.",
    "cand_A": "Anne's vase cracked in the move.",
    "cand_B": "A vase of Anne's cracked in the move."
   },
   {
    "item": "poss-06",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Carol has five sweaters.",
    "cand_A": "Carol's sweater shrank in the wash.",
    "cand_B": "A sweater of Carol's shrank in the wash."
   },
   {
    "item": "poss-08",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Sally has exactly one chair.",
    "cand_A": "Sally's chair collapsed last week.",
    "cand_B": "A chair of Sally's collapsed last week."
   },
   {
    "item": "poss-10",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Elizabeth has five boxes.",
    "cand_A": "Elizabeth's box arrived damaged.",
    "cand_B": "A box of Elizabeth's arrived damaged."
   },
   {
    "item": "poss-12",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Rachelle has written exactly one story.",
    "cand_A": "Rachelle's story won an award.",
    "cand_B": "A story of Rachelle's won an award."
   },
   {
    "item": "poss-14",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Kirsten has five forks.",
    "cand_A": "Kirsten's fork went missing.",
    "cand_B": "A fork of Kirsten's went missing."
   },
   {
    "item": "cleft-01",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone broke the window.",
    "cand_A": "It was Margaret who broke the window.",
    "cand_B": "Margaret broke the window."
   },
   {
    "item": "cleft-03",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody found the keys.",
    "cand_A": "It was Amanda who found the keys.",
    "cand_B": "Amanda found the keys."
   },
   {
    "item": "cleft-05",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone sent the email.",
    "cand_A": "It was Karla who sent the email.",
    "cand_B": "Karla sent the email."
   },
   {
    "item": "cleft-07",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody wrote the report.",
    "cand_A": "It was Helen who wrote the report.",
    "cand_B": "Helen wrote the report."
   },
   {
    "item": "cleft-09",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone locked the door.",
    "cand_A": "It was Vincent who locked the door.",
    "cand_B": "Vincent locked the door."
   },
   {
    "item": "cleft-11",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody fixed the printer.",
    "cand_A": "It was Donald who fixed the printer.",
    "cand_B": "Donald fixed the printer."
   },
   {
    "item": "cleft-13",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone cleaned the kitchen.",
    "cand_A": "It was Christina who cleaned the kitchen.",
    "cand_B": "Christina cleaned the kitchen."
   },
   {
    "item": "cleft-15",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody moved the chairs.",
    "cand_A": "It was Sonia who moved the chairs.",
    "cand_B": "Sonia moved the chairs."
   }
  ],
  "4": [
   {
    "item": "def-02",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The shelter has five dogs.",
    "cand_A": "The dog at the shelter is friendly.",
    "cand_B": "A dog at the shelter is friendly."
   },
   {
    "item": "def-04",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The garage has exactly one car.",
    "cand_A": "The car in the garage is red.",
    "cand_B": "A car in the garage is red."
   },
   {
    "item": "def-06",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The classroom has five clocks.",
    "cand_A": "The clock in the classroom is slow.",
    "cand_B": "A clock in the classroom is slow."
   },
   {
    "item": "def-08",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The bathroom has exactly one towel.",
    "cand_A": "The towel in the bathroom is wet.",
    "cand_B": "A towel in the bathroom is wet."
   },
   {
    "item": "def-10",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The drawer has five keys.",
    "cand_A": "The key in the drawer is rusty.",
    "cand_B": "A key in the drawer is rusty."
   },
   {
    "item": "def-12",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The library has exactly one computer.",
    "cand_A": "The computer in the library is frozen.",
    "cand_B": "A computer in the library is frozen."
   },
   {
    "item": "def-14",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The bedroom has five mirrors.",
    "cand_A": "The mirror in the bedroom is cracked.",
    "cand_B": "A mirror in the bedroom is cracked."
   },
   {
    "item": "dual-01",
    "cls": "duality",
    "ctx": "Control",
    "context": "Nina has four brothers.",
    "cand_A": "Both of her brothers are doctors.",
    "cand_B": "All of her brothers are doctors."
   },
   {
    "item": "dual-03",
    "cls": "duality",
    "ctx": "Support",
    "context": "Priya has exactly two cats.",
    "cand_A": "Both of her cats are asleep.",
    "cand_B": "All of her cats are asleep."
   },
   {
    "item": "dual-05",
    "cls": "duality",
    "ctx": "Control",
    "context": "Lena has four children.",
    "cand_A": "Both of her children are at school.",
    "cand_B": "All of her children are at school."
   },
   {
    "item": "dual-07",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ruth has exactly two plants.",
    "cand_A": "Both of her plants have died.",
    "cand_B": "All of her plants have died."
   },
   {
    "item": "dual-09",
    "cls": "duality",
    "ctx": "Control",
    "context": "Hana has four sons.",
    "cand_A": "Both of her sons are engineers.",
    "cand_B": "All of her sons are engineers."
   },
   {
    "item": "dual-11",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ada has exactly two daughters.",
    "cand_A": "Both of her daughters are married.",
    "cand_B": "All of her daughters are married."
   },
   {
    "item": "dual-13",
    "cls": "duality",
    "ctx": "Control",
    "context": "Iris has four houses.",
    "cand_A": "Both of her houses are rented out.",
    "cand_B": "All of her houses are rented out."
   },
   {
    "item": "dual-15",
    "cls": "duality",
    "ctx": "Support",
    "context": "Mei has exactly two suitcases.",
    "cand_A": "Both of her suitcases were lost.",
    "cand_B": "All of her suitcases were lost."
   },
   {
    "item": "add-02",
    "cls": "additive",
    "ctx": "Support",
    "context": "Lisa saw Dune.",
    "cand_A": "Donald saw Dune too.",
    "cand_B": "Donald saw Dune."
   },
   {
    "item": "add-04",
    "cls": "additive",
    "ctx": "Control",
    "context": "Anna didn't win a prize.",
    "cand_A": "Kate won a prize too.",
    "cand_B": "Kate won a prize."
   },
   {
    "item": "add-06",
    "cls": "additive",
    "ctx": "Support",
    "context": "Mia ordered the soup.",
    "cand_A": "Josh ordered the soup too.",
    "cand_B": "Josh ordered the soup."
   },
   {
    "item": "add-08",
    "cls": "additive",
    "ctx": "Control",
    "context": "Chloe didn't vote for the proposal.",
    "cand_A": "Dan voted for the proposal too.",
    "cand_B": "Dan voted for the proposal."
   },
   {
    "item": "add-10",
    "cls": "additive",
    "ctx": "Support",
    "context": "Nora signed the petition.",
    "cand_A": "Felix signed the petition too.",
    "cand_B": "Felix signed the petition."
   },
   {
    "item": "add-12",
    "cls": "additive",
    "ctx": "Control",
    "context": "Grace didn't join the gym.",
    "cand_A": "Owen joined the gym too.",
    "cand_B": "Owen joined the gym."
   },
   {
    "item": "add-14",
    "cls": "additive",
    "ctx": "Support",
    "context": "Hugo bought a ticket.",
    "cand_A": "Amy bought a ticket too.",
    "cand_B": "Amy bought a ticket."
   },
   {
    "item": "it-01",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Jenna had never been ice skating.",
    "cand_A": "She went ice skating again today.",
    "cand_B": "She went ice skating today."
   },
   {
    "item": "it-03",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Aisha cooked a curry yesterday.",
    "cand_A": "She cooked a curry again today.",
    "cand_B": "She cooked a curry today."
   },
   {
    "item": "it-05",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Yuki had never visited Paris.",
    "cand_A": "She visited Paris again today.",
    "cand_B": "She visited Paris today."
   },
   {
    "item": "it-07",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Clara fell off her bike yesterday.",
    "cand_A": "She fell off her bike again today.",
    "cand_B": "She fell off her bike today."
   },
   {
    "item": "it-09",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Lina had never baked bread.",
    "cand_A": "She baked bread again today.",
    "cand_B": "She baked bread today."
   },
   {
    "item": "it-11",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Fay went swimming yesterday.",
    "cand_A": "She went swimming again today.",
    "cand_B": "She went swimming today."
   },
   {
    "item": "it-13",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Before today, Maya had never sung in public.",
    "cand_A": "She sang in public again today.",
    "cand_B": "She sang in public today."
   },
   {
    "item": "it-15",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Noor rode a horse yesterday.",
    "cand_A": "She rode a horse again today.",
    "cand_B": "She rode a horse today."
   },
   {
    "item": "fact-02",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The key is not under the mat, though a rumour says otherwise.",
    "cand_A": "Ruth knows that the key is under the mat.",
    "cand_B": "Ruth believes that the key is under the mat."
   },
   {
    "item": "fact-04",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The shop is closed today.",
    "cand_A": "Bea knows that the shop is closed today.",
    "cand_B": "Bea believes that the shop is closed today."
   },
   {
    "item": "fact-06",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The exam has not been postponed, though a rumour says otherwise.",
    "cand_A": "Dina knows that the exam has been postponed.",
    "cand_B": "Dina believes that the exam has been postponed."
   },
   {
    "item": "fact-08",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The concert sold out.",
    "cand_A": "Fran knows that the concert sold out.",
    "cand_B": "Fran believes that the concert sold out."
   },
   {
    "item": "fact-10",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The milk has not gone off, though a rumour says otherwise.",
    "cand_A": "Hal knows that the milk has gone off.",
    "cand_B": "Hal believes that the milk has gone off."
   },
   {
    "item": "fact-12",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The printer is broken.",
    "cand_A": "Jay knows that the printer is broken.",
    "cand_B": "Jay believes that the printer is broken."
   },
   {
    "item": "fact-14",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The tickets are not free, though a rumour says otherwise.",
    "cand_A": "Lou knows that the tickets are free.",
    "cand_B": "Lou believes that the tickets are free."
   },
   {
    "item": "cos-01",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Scott has never smoked.",
    "cand_A": "Scott stopped smoking.",
    "cand_B": "Scott doesn't smoke."
   },
   {
    "item": "cos-03",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Iris used to play the piano.",
    "cand_A": "Iris stopped playing the piano.",
    "cand_B": "Iris doesn't play the piano."
   },
   {
    "item": "cos-05",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Nell has never eaten meat.",
    "cand_A": "Nell stopped eating meat.",
    "cand_B": "Nell doesn't eat meat."
   },
   {
    "item": "cos-07",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Pia used to go to church.",
    "cand_A": "Pia stopped going to church.",
    "cand_B": "Pia doesn't go to church."
   },
   {
    "item": "cos-09",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Rosa has never written poetry.",
    "cand_A": "Rosa stopped writing poetry.",
    "cand_B": "Rosa doesn't write poetry."
   },
   {
    "item": "cos-11",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Tess used to sing in a choir.",
    "cand_A": "Tess stopped singing in a choir.",
    "cand_B": "Tess doesn't sing in a choir."
   },
   {
    "item": "cos-13",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Maybe Vera has never worn glasses.",
    "cand_A": "Vera stopped wearing glasses.",
    "cand_B": "Vera doesn't wear glasses."
   },
   {
    "item": "cos-15",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Xavi used to take the bus.",
    "cand_A": "Xavi stopped taking the bus.",
    "cand_B": "Xavi doesn't take the bus."
   },
   {
    "item": "poss-02",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Deanna has exactly one ladder.",
    "cand_A": "Deanna's ladder was stolen.",
    "cand_B": "A ladder of Deanna's was stolen."
   },
   {
    "item": "poss-04",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Anne has three vases.",
    "cand_A": "Anne's vase cracked in the move.",
    "cand_B": "A vase of Anne's cracked in the move."
   },
   {
    "item": "poss-06",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Carol has exactly one sweater.",
    "cand_A": "Carol's sweater shrank in the wash.",
    "cand_B": "A sweater of Carol's shrank in the wash."
   },
   {
    "item": "poss-08",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Sally has three chairs.",
    "cand_A": "Sally's chair collapsed last week.",
    "cand_B": "A chair of Sally's collapsed last week."
   },
   {
    "item": "poss-10",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Elizabeth has exactly one box.",
    "cand_A": "Elizabeth's box arrived damaged.",
    "cand_B": "A box of Elizabeth's arrived damaged."
   },
   {
    "item": "poss-12",
    "cls": "possessive",
    "ctx": "Control",
    "context": "Rachelle has written three stories.",
    "cand_A": "Rachelle's story won an award.",
    "cand_B": "A story of Rachelle's won an award."
   },
   {
    "item": "poss-14",
    "cls": "possessive",
    "ctx": "Support",
    "context": "Kirsten has exactly one fork.",
    "cand_A": "Kirsten's fork went missing.",
    "cand_B": "A fork of Kirsten's went missing."
   },
   {
    "item": "cleft-01",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody broke the window.",
    "cand_A": "It was Margaret who broke the window.",
    "cand_B": "Margaret broke the window."
   },
   {
    "item": "cleft-03",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone found the keys.",
    "cand_A": "It was Amanda who found the keys.",
    "cand_B": "Amanda found the keys."
   },
   {
    "item": "cleft-05",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody sent the email.",
    "cand_A": "It was Karla who sent the email.",
    "cand_B": "Karla sent the email."
   },
   {
    "item": "cleft-07",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone wrote the report.",
    "cand_A": "It was Helen who wrote the report.",
    "cand_B": "Helen wrote the report."
   },
   {
    "item": "cleft-09",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody locked the door.",
    "cand_A": "It was Vincent who locked the door.",
    "cand_B": "Vincent locked the door."
   },
   {
    "item": "cleft-11",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone fixed the printer.",
    "cand_A": "It was Donald who fixed the printer.",
    "cand_B": "Donald fixed the printer."
   },
   {
    "item": "cleft-13",
    "cls": "cleft",
    "ctx": "Control",
    "context": "Maybe nobody cleaned the kitchen.",
    "cand_A": "It was Christina who cleaned the kitchen.",
    "cand_B": "Christina cleaned the kitchen."
   },
   {
    "item": "cleft-15",
    "cls": "cleft",
    "ctx": "Support",
    "context": "Someone moved the chairs.",
    "cand_A": "It was Sonia who moved the chairs.",
    "cand_B": "Sonia moved the chairs."
   }
  ]
 },
 "fillers": [
  {
   "item": "fill-01",
   "cls": "filler",
   "ctx": "fit",
   "context": "It was freezing outside.",
   "cand_A": "Tom put on his coat.",
   "cand_B": "Tom put on his sandals.",
   "filler_key": "A"
  },
  {
   "item": "fill-02",
   "cls": "filler",
   "ctx": "fit",
   "context": "Anna was very thirsty.",
   "cand_A": "She asked for some water.",
   "cand_B": "She asked for some bread.",
   "filler_key": "A"
  },
  {
   "item": "fill-03",
   "cls": "filler",
   "ctx": "fit",
   "context": "Mark forgot his umbrella.",
   "cand_A": "He got wet on the way home.",
   "cand_B": "He got dry on the way home.",
   "filler_key": "A"
  },
  {
   "item": "fill-04",
   "cls": "filler",
   "ctx": "fit",
   "context": "The lecture was very boring.",
   "cand_A": "Several students yawned.",
   "cand_B": "Several students cheered.",
   "filler_key": "A"
  },
  {
   "item": "fill-05",
   "cls": "filler",
   "ctx": "fit",
   "context": "Kate's flight left at dawn.",
   "cand_A": "She got up early.",
   "cand_B": "She got up late.",
   "filler_key": "A"
  },
  {
   "item": "fill-06",
   "cls": "filler",
   "ctx": "fit",
   "context": "The soup was very salty.",
   "cand_A": "Raj added more water.",
   "cand_B": "Raj added more salt.",
   "filler_key": "A"
  },
  {
   "item": "fill-07",
   "cls": "filler",
   "ctx": "fit",
   "context": "The exam was very easy.",
   "cand_A": "Most students passed.",
   "cand_B": "Most students failed.",
   "filler_key": "A"
  },
  {
   "item": "fill-08",
   "cls": "filler",
   "ctx": "fit",
   "context": "The room was very dark.",
   "cand_A": "Jo switched on the light.",
   "cand_B": "Jo switched off the light.",
   "filler_key": "A"
  },
  {
   "item": "fill-09",
   "cls": "filler",
   "ctx": "fit",
   "context": "Luis won the lottery.",
   "cand_A": "He was delighted.",
   "cand_B": "He was furious.",
   "filler_key": "A"
  },
  {
   "item": "fill-10",
   "cls": "filler",
   "ctx": "fit",
   "context": "The baby was exhausted.",
   "cand_A": "He fell asleep quickly.",
   "cand_B": "He woke up quickly.",
   "filler_key": "A"
  },
  {
   "item": "fill-11",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The shop was closed.",
   "cand_A": "Ella could not buy milk.",
   "cand_B": "Ella could buy milk.",
   "filler_key": "A"
  },
  {
   "item": "fill-12",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The road was flooded.",
   "cand_A": "Sam could not drive home.",
   "cand_B": "Sam could drive home.",
   "filler_key": "A"
  },
  {
   "item": "fill-13",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "Lucy had lost her voice.",
   "cand_A": "She could not sing.",
   "cand_B": "She could sing.",
   "filler_key": "A"
  },
  {
   "item": "fill-14",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The printer was out of ink.",
   "cand_A": "Omar could not print his essay.",
   "cand_B": "Omar could print his essay.",
   "filler_key": "A"
  },
  {
   "item": "fill-15",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "Hannah missed the last bus.",
   "cand_A": "She could not get home.",
   "cand_B": "She could get home.",
   "filler_key": "A"
  },
  {
   "item": "fill-16",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The ice was very thin.",
   "cand_A": "The children could not skate.",
   "cand_B": "The children could skate.",
   "filler_key": "A"
  },
  {
   "item": "fill-17",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The concert was sold out.",
   "cand_A": "Nadia could not get a ticket.",
   "cand_B": "Nadia could get a ticket.",
   "filler_key": "A"
  },
  {
   "item": "fill-18",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "Ben's phone was dead.",
   "cand_A": "He could not call his sister.",
   "cand_B": "He could call his sister.",
   "filler_key": "A"
  },
  {
   "item": "fill-19",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The café had free tables.",
   "cand_A": "Jo could sit down.",
   "cand_B": "Jo could not sit down.",
   "filler_key": "A"
  },
  {
   "item": "fill-20",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The bakery still had bread.",
   "cand_A": "Tim could buy a loaf.",
   "cand_B": "Tim could not buy a loaf.",
   "filler_key": "A"
  },
  {
   "item": "fill-21",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "Amy found her keys.",
   "cand_A": "She could open the door.",
   "cand_B": "She could not open the door.",
   "filler_key": "A"
  },
  {
   "item": "fill-22",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "It was sunny.",
   "cand_A": "The kids could play outside.",
   "cand_B": "The kids could not play outside.",
   "filler_key": "A"
  },
  {
   "item": "fill-23",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The pool was open.",
   "cand_A": "Zara could swim.",
   "cand_B": "Zara could not swim.",
   "filler_key": "A"
  },
  {
   "item": "fill-24",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "Chris fixed his bike.",
   "cand_A": "He could ride to work.",
   "cand_B": "He could not ride to work.",
   "filler_key": "A"
  },
  {
   "item": "fill-25",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The Wi-Fi was working.",
   "cand_A": "Ivy could send the email.",
   "cand_B": "Ivy could not send the email.",
   "filler_key": "A"
  },
  {
   "item": "fill-26",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The tickets were cheap.",
   "cand_A": "Paul could afford one.",
   "cand_B": "Paul could not afford one.",
   "filler_key": "A"
  },
  {
   "item": "fill-27",
   "cls": "filler",
   "ctx": "tense",
   "context": "Carl cooked dinner last night.",
   "cand_A": "Then he washed the dishes.",
   "cand_B": "Then he washes the dishes.",
   "filler_key": "A"
  },
  {
   "item": "fill-28",
   "cls": "filler",
   "ctx": "tense",
   "context": "Ian stayed in last night.",
   "cand_A": "He watched a film.",
   "cand_B": "He watches a film.",
   "filler_key": "A"
  },
  {
   "item": "fill-29",
   "cls": "filler",
   "ctx": "tense",
   "context": "Rosa went to Rome last summer.",
   "cand_A": "She saw the Colosseum.",
   "cand_B": "She sees the Colosseum.",
   "filler_key": "A"
  },
  {
   "item": "fill-30",
   "cls": "filler",
   "ctx": "tense",
   "context": "The storm hit last Friday.",
   "cand_A": "It knocked down a tree.",
   "cand_B": "It knocks down a tree.",
   "filler_key": "A"
  },
  {
   "item": "fill-31",
   "cls": "filler",
   "ctx": "tense",
   "context": "Alex had a party on Saturday.",
   "cand_A": "Twenty friends came.",
   "cand_B": "Twenty friends come.",
   "filler_key": "A"
  },
  {
   "item": "fill-32",
   "cls": "filler",
   "ctx": "tense",
   "context": "Grace baked a cake this morning.",
   "cand_A": "Her sons ate it.",
   "cand_B": "Her sons eat it.",
   "filler_key": "A"
  },
  {
   "item": "fill-33",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Ella looked pale.",
   "cand_A": "Her friend thought that she was ill.",
   "cand_B": "Her friend thought she was ill.",
   "filler_key": null
  },
  {
   "item": "fill-34",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Dan came home late.",
   "cand_A": "He said that the train was delayed.",
   "cand_B": "He said the train was delayed.",
   "filler_key": null
  },
  {
   "item": "fill-35",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "The fridge was empty.",
   "cand_A": "Maya thought that she should go shopping.",
   "cand_B": "Maya thought she should go shopping.",
   "filler_key": null
  },
  {
   "item": "fill-36",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Leo checked the forecast.",
   "cand_A": "It said that rain was coming.",
   "cand_B": "It said rain was coming.",
   "filler_key": null
  },
  {
   "item": "fill-37",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Sophie opened the letter.",
   "cand_A": "It said that she had got the job.",
   "cand_B": "It said she had got the job.",
   "filler_key": null
  },
  {
   "item": "fill-38",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Jamal looked at the sky.",
   "cand_A": "He guessed that it would rain.",
   "cand_B": "He guessed it would rain.",
   "filler_key": null
  },
  {
   "item": "fill-39",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "The team lost the match.",
   "cand_A": "The coach said that they needed more practice.",
   "cand_B": "The coach said they needed more practice.",
   "filler_key": null
  },
  {
   "item": "fill-40",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Olivia studied every evening.",
   "cand_A": "She hoped that the exam would be easy.",
   "cand_B": "She hoped the exam would be easy.",
   "filler_key": null
  },
  {
   "item": "fill-41",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Ann was moving house.",
   "cand_A": "Tom helped her to pack the boxes.",
   "cand_B": "Tom helped her pack the boxes.",
   "filler_key": null
  },
  {
   "item": "fill-42",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "The kitchen was a mess.",
   "cand_A": "Sara helped Paul to clean it.",
   "cand_B": "Sara helped Paul clean it.",
   "filler_key": null
  },
  {
   "item": "fill-43",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Grandpa's car broke down.",
   "cand_A": "His neighbour helped him to push it.",
   "cand_B": "His neighbour helped him push it.",
   "filler_key": null
  },
  {
   "item": "fill-44",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Lily was new at school.",
   "cand_A": "Her teacher helped her to find the library.",
   "cand_B": "Her teacher helped her find the library.",
   "filler_key": null
  },
  {
   "item": "fill-45",
   "cls": "filler",
   "ctx": "particle",
   "context": "Jo's coat was on the floor.",
   "cand_A": "She picked the coat up.",
   "cand_B": "She picked up the coat.",
   "filler_key": null
  },
  {
   "item": "fill-46",
   "cls": "filler",
   "ctx": "particle",
   "context": "The music was very loud.",
   "cand_A": "Rob turned the radio down.",
   "cand_B": "Rob turned down the radio.",
   "filler_key": null
  },
  {
   "item": "fill-47",
   "cls": "filler",
   "ctx": "particle",
   "context": "The form had a mistake.",
   "cand_A": "Kim crossed the mistake out.",
   "cand_B": "Kim crossed out the mistake.",
   "filler_key": null
  },
  {
   "item": "fill-48",
   "cls": "filler",
   "ctx": "particle",
   "context": "It got dark early.",
   "cand_A": "Dad switched the lamp on.",
   "cand_B": "Dad switched on the lamp.",
   "filler_key": null
  },
  {
   "item": "fill-49",
   "cls": "filler",
   "ctx": "particle",
   "context": "Ivan finished his cereal.",
   "cand_A": "He put the bowl away.",
   "cand_B": "He put away the bowl.",
   "filler_key": null
  },
  {
   "item": "fill-50",
   "cls": "filler",
   "ctx": "particle",
   "context": "The meeting clashed with lunch.",
   "cand_A": "Priya called the meeting off.",
   "cand_B": "Priya called off the meeting.",
   "filler_key": null
  },
  {
   "item": "fill-51",
   "cls": "filler",
   "ctx": "particle",
   "context": "The shoes did not fit.",
   "cand_A": "Ella took the shoes back.",
   "cand_B": "Ella took back the shoes.",
   "filler_key": null
  },
  {
   "item": "fill-52",
   "cls": "filler",
   "ctx": "particle",
   "context": "Max found an old letter.",
   "cand_A": "He threw the letter away.",
   "cand_B": "He threw away the letter.",
   "filler_key": null
  },
  {
   "item": "fill-53",
   "cls": "filler",
   "ctx": "dative",
   "context": "Mary needed a pen.",
   "cand_A": "Jack gave Mary a pen.",
   "cand_B": "Jack gave a pen to Mary.",
   "filler_key": null
  },
  {
   "item": "fill-54",
   "cls": "filler",
   "ctx": "dative",
   "context": "Grandma loves photos.",
   "cand_A": "Liam sent Grandma a photo.",
   "cand_B": "Liam sent a photo to Grandma.",
   "filler_key": null
  },
  {
   "item": "fill-55",
   "cls": "filler",
   "ctx": "dative",
   "context": "The waiter brought the bill.",
   "cand_A": "Ruth handed the waiter her card.",
   "cand_B": "Ruth handed her card to the waiter.",
   "filler_key": null
  },
  {
   "item": "fill-56",
   "cls": "filler",
   "ctx": "dative",
   "context": "Sam's niece turned five.",
   "cand_A": "Sam bought his niece a kite.",
   "cand_B": "Sam bought a kite for his niece.",
   "filler_key": null
  },
  {
   "item": "fill-57",
   "cls": "filler",
   "ctx": "dative",
   "context": "Noah wrote a long letter.",
   "cand_A": "He sent his cousin the letter.",
   "cand_B": "He sent the letter to his cousin.",
   "filler_key": null
  },
  {
   "item": "fill-58",
   "cls": "filler",
   "ctx": "dative",
   "context": "Chloe baked some cookies.",
   "cand_A": "She offered her neighbour a cookie.",
   "cand_B": "She offered a cookie to her neighbour.",
   "filler_key": null
  },
  {
   "item": "fill-59",
   "cls": "filler",
   "ctx": "dative",
   "context": "The teacher had the exam results.",
   "cand_A": "She showed the class the results.",
   "cand_B": "She showed the results to the class.",
   "filler_key": null
  },
  {
   "item": "fill-60",
   "cls": "filler",
   "ctx": "dative",
   "context": "Tariq had an old guitar.",
   "cand_A": "He sold a student the guitar.",
   "cand_B": "He sold the guitar to a student.",
   "filler_key": null
  }
 ],
 "attention": [
  {
   "item": "check-1",
   "cls": "check",
   "ctx": "check",
   "context": "Ravi bought a blue bicycle.",
   "cand_A": "Ravi's bicycle is blue.",
   "cand_B": "Ravi's bicycle is and."
  },
  {
   "item": "check-2",
   "cls": "check",
   "ctx": "check",
   "context": "The bakery closes at six.",
   "cand_A": "The bakery closes at six.",
   "cand_B": "The bakery closes at purple."
  },
  {
   "item": "check-3",
   "cls": "check",
   "ctx": "check",
   "context": "Nadia was in Rome last week.",
   "cand_A": "Nadia came back from Rome.",
   "cand_B": "Nadia came back from slowly."
  },
  {
   "item": "check-4",
   "cls": "check",
   "ctx": "check",
   "context": "A cat is lying in the garden.",
   "cand_A": "The cat in the garden is asleep.",
   "cand_B": "The cat in the garden is of."
  },
  {
   "item": "check-5",
   "cls": "check",
   "ctx": "check",
   "context": "Theo had maths homework.",
   "cand_A": "Theo finished his homework.",
   "cand_B": "Theo finished his the."
  },
  {
   "item": "check-6",
   "cls": "check",
   "ctx": "check",
   "context": "The train to Leeds leaves at noon.",
   "cand_A": "The train leaves at noon.",
   "cand_B": "The train leaves at under."
  }
 ],
 "practice": [
  {
   "item": "prac-1",
   "cls": "practice",
   "ctx": "practice",
   "context": "Maya has exactly one umbrella.",
   "cand_A": "Maya's umbrella is broken.",
   "cand_B": "An umbrella of Maya's is broken."
  },
  {
   "item": "prac-2",
   "cls": "practice",
   "ctx": "practice",
   "context": "Leo went to the cinema on Friday.",
   "cand_A": "He went to the cinema again on Saturday.",
   "cand_B": "He went to the cinema on Saturday."
  },
  {
   "item": "prac-3",
   "cls": "practice",
   "ctx": "practice",
   "context": "Ellie spilled juice on the table.",
   "cand_A": "She wiped the table down.",
   "cand_B": "She wiped down the table."
  }
 ]
};
if (typeof module !== "undefined") module.exports = { STIMULI };
