// Generated by build-stimuli.mjs. Do not edit by hand.
const STIMULI = {
 "lists": {
  "1": [
   {
    "item": "def-01",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "Our kitchen only has one window.",
    "cand_A": "I opened the window this morning.",
    "cand_B": "I opened a window this morning."
   },
   {
    "item": "def-03",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "My office has a lot of lamps.",
    "cand_A": "I switched on the lamp.",
    "cand_B": "I switched on a lamp."
   },
   {
    "item": "def-05",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The classroom only had one clock.",
    "cand_A": "Someone broke the clock.",
    "cand_B": "Someone broke a clock."
   },
   {
    "item": "def-07",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The bathroom had plenty of towels.",
    "cand_A": "I dried my hands on the towel.",
    "cand_B": "I dried my hands on a towel."
   },
   {
    "item": "def-09",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The drawer only had one key in it.",
    "cand_A": "I tried the key in the lock.",
    "cand_B": "I tried a key in the lock."
   },
   {
    "item": "def-11",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The library has twenty computers.",
    "cand_A": "Someone was using the computer.",
    "cand_B": "Someone was using a computer."
   },
   {
    "item": "def-13",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The bedroom only has one mirror.",
    "cand_A": "There's a crack in the mirror.",
    "cand_B": "There's a crack in a mirror."
   },
   {
    "item": "def-15",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The hotel had several lifts.",
    "cand_A": "The lift was out of order.",
    "cand_B": "A lift was out of order."
   },
   {
    "item": "part-02",
    "cls": "partitive",
    "ctx": "Support",
    "context": "My sister only has one cat.",
    "cand_A": "The cat scratched me.",
    "cand_B": "One of the cats scratched me."
   },
   {
    "item": "part-04",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The team has several coaches.",
    "cand_A": "I spoke to the coach after the match.",
    "cand_B": "I spoke to one of the coaches after the match."
   },
   {
    "item": "part-06",
    "cls": "partitive",
    "ctx": "Support",
    "context": "My desk only has one drawer.",
    "cand_A": "The drawer keeps getting stuck.",
    "cand_B": "One of the drawers keeps getting stuck."
   },
   {
    "item": "part-08",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The printer has three trays.",
    "cand_A": "I filled the tray with paper.",
    "cand_B": "I filled one of the trays with paper."
   },
   {
    "item": "part-10",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The school only has one nurse.",
    "cand_A": "I phoned the nurse this morning.",
    "cand_B": "I phoned one of the nurses this morning."
   },
   {
    "item": "part-12",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The course had a lot of exams.",
    "cand_A": "I failed the exam.",
    "cand_B": "I failed one of the exams."
   },
   {
    "item": "part-14",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The hotel only had one pool.",
    "cand_A": "We swam in the pool every day.",
    "cand_B": "We swam in one of the pools every day."
   },
   {
    "item": "part-16",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The farm had several tractors.",
    "cand_A": "My uncle let me drive the tractor.",
    "cand_B": "My uncle let me drive one of the tractors."
   },
   {
    "item": "dual-01",
    "cls": "duality",
    "ctx": "Support",
    "context": "My aunt only has two dogs.",
    "cand_A": "Both of her dogs are very old.",
    "cand_B": "All of her dogs are very old."
   },
   {
    "item": "dual-03",
    "cls": "duality",
    "ctx": "Control",
    "context": "Priya has lots of cats.",
    "cand_A": "She feeds both of her cats twice a day.",
    "cand_B": "She feeds all of her cats twice a day."
   },
   {
    "item": "dual-05",
    "cls": "duality",
    "ctx": "Support",
    "context": "Our neighbours only have two children.",
    "cand_A": "Both of their children go to my school.",
    "cand_B": "All of their children go to my school."
   },
   {
    "item": "dual-07",
    "cls": "duality",
    "ctx": "Control",
    "context": "We ordered twenty pizzas.",
    "cand_A": "They were both delicious.",
    "cand_B": "They were all delicious."
   },
   {
    "item": "dual-09",
    "cls": "duality",
    "ctx": "Support",
    "context": "Hana only had two exams this term.",
    "cand_A": "She passed them both.",
    "cand_B": "She passed them all."
   },
   {
    "item": "dual-11",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ada has thirty grandchildren.",
    "cand_A": "She sends both of her grandchildren a card every year.",
    "cand_B": "She sends all of her grandchildren a card every year."
   },
   {
    "item": "dual-13",
    "cls": "duality",
    "ctx": "Support",
    "context": "The shop only had two bikes left.",
    "cand_A": "I tried both of them.",
    "cand_B": "I tried all of them."
   },
   {
    "item": "dual-15",
    "cls": "duality",
    "ctx": "Control",
    "context": "Mei packed seven suitcases.",
    "cand_A": "The airline lost both of her suitcases.",
    "cand_B": "The airline lost all of her suitcases."
   },
   {
    "item": "add-02",
    "cls": "additive",
    "ctx": "Support",
    "context": "John came to the party.",
    "cand_A": "Bill came to the party too.",
    "cand_B": "Bill came to the party."
   },
   {
    "item": "add-04",
    "cls": "additive",
    "ctx": "Control",
    "context": "Anna left the fair empty-handed.",
    "cand_A": "Kate won a prize too.",
    "cand_B": "Kate won a prize."
   },
   {
    "item": "add-06",
    "cls": "additive",
    "ctx": "Support",
    "context": "Raj read the report.",
    "cand_A": "Emma read the report too.",
    "cand_B": "Emma read the report."
   },
   {
    "item": "add-08",
    "cls": "additive",
    "ctx": "Control",
    "context": "Omar missed the early train.",
    "cand_A": "Lucy caught the early train too.",
    "cand_B": "Lucy caught the early train."
   },
   {
    "item": "add-10",
    "cls": "additive",
    "ctx": "Support",
    "context": "We visited the castle.",
    "cand_A": "Our friends visited the castle too.",
    "cand_B": "Our friends visited the castle."
   },
   {
    "item": "add-12",
    "cls": "additive",
    "ctx": "Control",
    "context": "Nora forgot to plant beans this year.",
    "cand_A": "Her neighbour planted beans too.",
    "cand_B": "Her neighbour planted beans."
   },
   {
    "item": "add-14",
    "cls": "additive",
    "ctx": "Support",
    "context": "Grace joined the gym in January.",
    "cand_A": "Owen also joined the gym.",
    "cand_B": "Owen joined the gym."
   },
   {
    "item": "add-16",
    "cls": "additive",
    "ctx": "Control",
    "context": "Hugo couldn't get a ticket for the final.",
    "cand_A": "Amy also bought a ticket.",
    "cand_B": "Amy bought a ticket."
   },
   {
    "item": "it-01",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Jenna went ice skating yesterday.",
    "cand_A": "She went ice skating again today.",
    "cand_B": "She went ice skating today."
   },
   {
    "item": "it-03",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Aisha cooked a stew on Monday.",
    "cand_A": "She cooked a curry again on Friday.",
    "cand_B": "She cooked a curry on Friday."
   },
   {
    "item": "it-05",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Freya visited Paris in May.",
    "cand_A": "She visited Paris again in June.",
    "cand_B": "She visited Paris in June."
   },
   {
    "item": "it-07",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Clara fell over in the park last week.",
    "cand_A": "She fell off her bike again yesterday.",
    "cand_B": "She fell off her bike yesterday."
   },
   {
    "item": "it-09",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Our dog chewed the sofa last month.",
    "cand_A": "It chewed the sofa again today.",
    "cand_B": "It chewed the sofa today."
   },
   {
    "item": "it-11",
    "cls": "iterative",
    "ctx": "Control",
    "context": "We painted the hall in October.",
    "cand_A": "The heating broke again in December.",
    "cand_B": "The heating broke in December."
   },
   {
    "item": "it-13",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Maya sang at the open-mic night.",
    "cand_A": "She sang there again last night.",
    "cand_B": "She sang there last night."
   },
   {
    "item": "it-15",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Our train was cancelled in March.",
    "cand_A": "Our flight was delayed again in April.",
    "cand_B": "Our flight was delayed in April."
   },
   {
    "item": "fact-02",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The key is under the doormat as usual.",
    "cand_A": "Ruth knows it's under the doormat.",
    "cand_B": "Ruth thinks it's under the doormat."
   },
   {
    "item": "fact-04",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The shop might be closed today.",
    "cand_A": "My mum knows that it's closed.",
    "cand_B": "My mum thinks that it's closed."
   },
   {
    "item": "fact-06",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The exam has been postponed until June.",
    "cand_A": "Dina knows it has been postponed.",
    "cand_B": "Dina believes it has been postponed."
   },
   {
    "item": "fact-08",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The concert may have sold out already.",
    "cand_A": "Fran found out that it had sold out.",
    "cand_B": "Fran heard that it had sold out."
   },
   {
    "item": "fact-10",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The milk has definitely gone off.",
    "cand_A": "Hal realised that it had gone off.",
    "cand_B": "Hal thought that it had gone off."
   },
   {
    "item": "fact-12",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The printer might be broken.",
    "cand_A": "Jay knows that the printer is broken.",
    "cand_B": "Jay believes that the printer is broken."
   },
   {
    "item": "fact-14",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The tickets are free this year.",
    "cand_A": "Lou found out that they're free.",
    "cand_B": "Lou heard that they're free."
   },
   {
    "item": "fact-16",
    "cls": "factivity",
    "ctx": "Control",
    "context": "Our landlord may have sold the flat.",
    "cand_A": "My flatmate knows that he's sold it.",
    "cand_B": "My flatmate thinks that he's sold it."
   },
   {
    "item": "cos-01",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Scott used to smoke a lot.",
    "cand_A": "He stopped smoking.",
    "cand_B": "He doesn't smoke."
   },
   {
    "item": "cos-03",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "My dad never ate meat as a child.",
    "cand_A": "He gave up meat.",
    "cand_B": "He doesn't eat meat."
   },
   {
    "item": "cos-05",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Owen used to bite his nails constantly.",
    "cand_A": "He stopped biting his nails.",
    "cand_B": "He doesn't bite his nails."
   },
   {
    "item": "cos-07",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Our teacher never needed glasses as a child.",
    "cand_A": "She stopped wearing glasses.",
    "cand_B": "She doesn't wear glasses."
   },
   {
    "item": "cos-09",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Tess used to sing in the church choir.",
    "cand_A": "She quit singing in a choir.",
    "cand_B": "She doesn't sing in a choir."
   },
   {
    "item": "cos-11",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Vera jogged every day at university.",
    "cand_A": "She started jogging.",
    "cand_B": "She jogs."
   },
   {
    "item": "cos-13",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Umar didn't use to watch the news.",
    "cand_A": "He started watching the news.",
    "cand_B": "He watches the news."
   },
   {
    "item": "cos-15",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Nell knitted a lot as a child.",
    "cand_A": "She took up knitting.",
    "cand_B": "She knits."
   }
  ],
  "2": [
   {
    "item": "def-01",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "Our kitchen has quite a few windows.",
    "cand_A": "I opened the window this morning.",
    "cand_B": "I opened a window this morning."
   },
   {
    "item": "def-03",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "My office only has one lamp.",
    "cand_A": "I switched on the lamp.",
    "cand_B": "I switched on a lamp."
   },
   {
    "item": "def-05",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The classroom had quite a few clocks.",
    "cand_A": "Someone broke the clock.",
    "cand_B": "Someone broke a clock."
   },
   {
    "item": "def-07",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The bathroom only had one towel.",
    "cand_A": "I dried my hands on the towel.",
    "cand_B": "I dried my hands on a towel."
   },
   {
    "item": "def-09",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The drawer had dozens of keys in it.",
    "cand_A": "I tried the key in the lock.",
    "cand_B": "I tried a key in the lock."
   },
   {
    "item": "def-11",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The library only has one computer.",
    "cand_A": "Someone was using the computer.",
    "cand_B": "Someone was using a computer."
   },
   {
    "item": "def-13",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The bedroom has mirrors on every wall.",
    "cand_A": "There's a crack in the mirror.",
    "cand_B": "There's a crack in a mirror."
   },
   {
    "item": "def-15",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The hotel only had one lift.",
    "cand_A": "The lift was out of order.",
    "cand_B": "A lift was out of order."
   },
   {
    "item": "part-02",
    "cls": "partitive",
    "ctx": "Control",
    "context": "My sister has three cats.",
    "cand_A": "The cat scratched me.",
    "cand_B": "One of the cats scratched me."
   },
   {
    "item": "part-04",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The team only has one coach.",
    "cand_A": "I spoke to the coach after the match.",
    "cand_B": "I spoke to one of the coaches after the match."
   },
   {
    "item": "part-06",
    "cls": "partitive",
    "ctx": "Control",
    "context": "My desk has a lot of drawers.",
    "cand_A": "The drawer keeps getting stuck.",
    "cand_B": "One of the drawers keeps getting stuck."
   },
   {
    "item": "part-08",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The printer only has one tray.",
    "cand_A": "I filled the tray with paper.",
    "cand_B": "I filled one of the trays with paper."
   },
   {
    "item": "part-10",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The school has several nurses.",
    "cand_A": "I phoned the nurse this morning.",
    "cand_B": "I phoned one of the nurses this morning."
   },
   {
    "item": "part-12",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The course only had one exam.",
    "cand_A": "I failed the exam.",
    "cand_B": "I failed one of the exams."
   },
   {
    "item": "part-14",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The hotel had three outdoor pools.",
    "cand_A": "We swam in the pool every day.",
    "cand_B": "We swam in one of the pools every day."
   },
   {
    "item": "part-16",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The farm only had one tractor.",
    "cand_A": "My uncle let me drive the tractor.",
    "cand_B": "My uncle let me drive one of the tractors."
   },
   {
    "item": "dual-01",
    "cls": "duality",
    "ctx": "Control",
    "context": "My aunt has a dozen dogs.",
    "cand_A": "Both of her dogs are very old.",
    "cand_B": "All of her dogs are very old."
   },
   {
    "item": "dual-03",
    "cls": "duality",
    "ctx": "Support",
    "context": "Priya only has two cats.",
    "cand_A": "She feeds both of her cats twice a day.",
    "cand_B": "She feeds all of her cats twice a day."
   },
   {
    "item": "dual-05",
    "cls": "duality",
    "ctx": "Control",
    "context": "Our neighbours have eight children.",
    "cand_A": "Both of their children go to my school.",
    "cand_B": "All of their children go to my school."
   },
   {
    "item": "dual-07",
    "cls": "duality",
    "ctx": "Support",
    "context": "We only ordered two pizzas.",
    "cand_A": "They were both delicious.",
    "cand_B": "They were all delicious."
   },
   {
    "item": "dual-09",
    "cls": "duality",
    "ctx": "Control",
    "context": "Hana had fifteen exams this term.",
    "cand_A": "She passed them both.",
    "cand_B": "She passed them all."
   },
   {
    "item": "dual-11",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ada only has two grandchildren.",
    "cand_A": "She sends both of her grandchildren a card every year.",
    "cand_B": "She sends all of her grandchildren a card every year."
   },
   {
    "item": "dual-13",
    "cls": "duality",
    "ctx": "Control",
    "context": "The shop had rows and rows of bikes.",
    "cand_A": "I tried both of them.",
    "cand_B": "I tried all of them."
   },
   {
    "item": "dual-15",
    "cls": "duality",
    "ctx": "Support",
    "context": "Mei only packed two suitcases.",
    "cand_A": "The airline lost both of her suitcases.",
    "cand_B": "The airline lost all of her suitcases."
   },
   {
    "item": "add-02",
    "cls": "additive",
    "ctx": "Control",
    "context": "John missed the party.",
    "cand_A": "Bill came to the party too.",
    "cand_B": "Bill came to the party."
   },
   {
    "item": "add-04",
    "cls": "additive",
    "ctx": "Support",
    "context": "Anna won a prize at the fair.",
    "cand_A": "Kate won a prize too.",
    "cand_B": "Kate won a prize."
   },
   {
    "item": "add-06",
    "cls": "additive",
    "ctx": "Control",
    "context": "Raj ignored the report.",
    "cand_A": "Emma read the report too.",
    "cand_B": "Emma read the report."
   },
   {
    "item": "add-08",
    "cls": "additive",
    "ctx": "Support",
    "context": "Omar caught the early train.",
    "cand_A": "Lucy caught the early train too.",
    "cand_B": "Lucy caught the early train."
   },
   {
    "item": "add-10",
    "cls": "additive",
    "ctx": "Control",
    "context": "We skipped the castle.",
    "cand_A": "Our friends visited the castle too.",
    "cand_B": "Our friends visited the castle."
   },
   {
    "item": "add-12",
    "cls": "additive",
    "ctx": "Support",
    "context": "Nora planted beans this year.",
    "cand_A": "Her neighbour planted beans too.",
    "cand_B": "Her neighbour planted beans."
   },
   {
    "item": "add-14",
    "cls": "additive",
    "ctx": "Control",
    "context": "Grace avoided the gym in January.",
    "cand_A": "Owen also joined the gym.",
    "cand_B": "Owen joined the gym."
   },
   {
    "item": "add-16",
    "cls": "additive",
    "ctx": "Support",
    "context": "Hugo bought a ticket for the final.",
    "cand_A": "Amy also bought a ticket.",
    "cand_B": "Amy bought a ticket."
   },
   {
    "item": "it-01",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Jenna went swimming yesterday.",
    "cand_A": "She went ice skating again today.",
    "cand_B": "She went ice skating today."
   },
   {
    "item": "it-03",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Aisha cooked a curry on Monday.",
    "cand_A": "She cooked a curry again on Friday.",
    "cand_B": "She cooked a curry on Friday."
   },
   {
    "item": "it-05",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Freya visited Rome in May.",
    "cand_A": "She visited Paris again in June.",
    "cand_B": "She visited Paris in June."
   },
   {
    "item": "it-07",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Clara fell off her bike last week.",
    "cand_A": "She fell off her bike again yesterday.",
    "cand_B": "She fell off her bike yesterday."
   },
   {
    "item": "it-09",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Our dog chewed a shoe last month.",
    "cand_A": "It chewed the sofa again today.",
    "cand_B": "It chewed the sofa today."
   },
   {
    "item": "it-11",
    "cls": "iterative",
    "ctx": "Support",
    "context": "The heating broke in October.",
    "cand_A": "The heating broke again in December.",
    "cand_B": "The heating broke in December."
   },
   {
    "item": "it-13",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Maya danced at the open-mic night.",
    "cand_A": "She sang there again last night.",
    "cand_B": "She sang there last night."
   },
   {
    "item": "it-15",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Our flight was delayed in March.",
    "cand_A": "Our flight was delayed again in April.",
    "cand_B": "Our flight was delayed in April."
   },
   {
    "item": "fact-02",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The key might be under the doormat.",
    "cand_A": "Ruth knows it's under the doormat.",
    "cand_B": "Ruth thinks it's under the doormat."
   },
   {
    "item": "fact-04",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The shop is closed all day today.",
    "cand_A": "My mum knows that it's closed.",
    "cand_B": "My mum thinks that it's closed."
   },
   {
    "item": "fact-06",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The exam might be postponed until June.",
    "cand_A": "Dina knows it has been postponed.",
    "cand_B": "Dina believes it has been postponed."
   },
   {
    "item": "fact-08",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The concert sold out in minutes.",
    "cand_A": "Fran found out that it had sold out.",
    "cand_B": "Fran heard that it had sold out."
   },
   {
    "item": "fact-10",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The milk might have gone off.",
    "cand_A": "Hal realised that it had gone off.",
    "cand_B": "Hal thought that it had gone off."
   },
   {
    "item": "fact-12",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The printer is broken.",
    "cand_A": "Jay knows that the printer is broken.",
    "cand_B": "Jay believes that the printer is broken."
   },
   {
    "item": "fact-14",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The tickets might be free.",
    "cand_A": "Lou found out that they're free.",
    "cand_B": "Lou heard that they're free."
   },
   {
    "item": "fact-16",
    "cls": "factivity",
    "ctx": "Support",
    "context": "Our landlord has sold the flat.",
    "cand_A": "My flatmate knows that he's sold it.",
    "cand_B": "My flatmate thinks that he's sold it."
   },
   {
    "item": "cos-01",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Scott never smoked as a student.",
    "cand_A": "He stopped smoking.",
    "cand_B": "He doesn't smoke."
   },
   {
    "item": "cos-03",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "My dad used to eat a lot of meat.",
    "cand_A": "He gave up meat.",
    "cand_B": "He doesn't eat meat."
   },
   {
    "item": "cos-05",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Owen never bit his nails as a child.",
    "cand_A": "He stopped biting his nails.",
    "cand_B": "He doesn't bite his nails."
   },
   {
    "item": "cos-07",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Our teacher used to wear thick glasses.",
    "cand_A": "She stopped wearing glasses.",
    "cand_B": "She doesn't wear glasses."
   },
   {
    "item": "cos-09",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Tess never sang in a choir at school.",
    "cand_A": "She quit singing in a choir.",
    "cand_B": "She doesn't sing in a choir."
   },
   {
    "item": "cos-11",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Vera didn't use to jog.",
    "cand_A": "She started jogging.",
    "cand_B": "She jogs."
   },
   {
    "item": "cos-13",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Umar watched the news daily as a student.",
    "cand_A": "He started watching the news.",
    "cand_B": "He watches the news."
   },
   {
    "item": "cos-15",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Nell didn't use to knit or sew.",
    "cand_A": "She took up knitting.",
    "cand_B": "She knits."
   }
  ],
  "3": [
   {
    "item": "def-02",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The shelter only had one dog.",
    "cand_A": "We adopted the dog last week.",
    "cand_B": "We adopted a dog last week."
   },
   {
    "item": "def-04",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "Our garden has a lot of trees.",
    "cand_A": "The tree is dying.",
    "cand_B": "A tree is dying."
   },
   {
    "item": "def-06",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The hallway only has one painting.",
    "cand_A": "I straightened the painting.",
    "cand_B": "I straightened a painting."
   },
   {
    "item": "def-08",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The fridge had a whole bag of pears.",
    "cand_A": "I ate the pear for lunch.",
    "cand_B": "I ate a pear for lunch."
   },
   {
    "item": "def-10",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "Our flat only has one radiator.",
    "cand_A": "I turned the radiator up.",
    "cand_B": "I turned a radiator up."
   },
   {
    "item": "def-12",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The field had several horses in it.",
    "cand_A": "The horse came over to the fence.",
    "cand_B": "A horse came over to the fence."
   },
   {
    "item": "def-14",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The shop only has one changing room.",
    "cand_A": "I waited outside the changing room.",
    "cand_B": "I waited outside a changing room."
   },
   {
    "item": "def-16",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "Our street has quite a few bakeries.",
    "cand_A": "I bought bread from the bakery.",
    "cand_B": "I bought bread from a bakery."
   },
   {
    "item": "part-01",
    "cls": "partitive",
    "ctx": "Support",
    "context": "Our street only has one café.",
    "cand_A": "We had lunch at the café.",
    "cand_B": "We had lunch at one of the cafés."
   },
   {
    "item": "part-03",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The flat had three big bedrooms.",
    "cand_A": "I painted the bedroom blue.",
    "cand_B": "I painted one of the bedrooms blue."
   },
   {
    "item": "part-05",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The museum only had one guide.",
    "cand_A": "The guide showed us around.",
    "cand_B": "One of the guides showed us around."
   },
   {
    "item": "part-07",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The village has quite a few pubs.",
    "cand_A": "We met in the pub on Friday.",
    "cand_B": "We met in one of the pubs on Friday."
   },
   {
    "item": "part-09",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The house only has one bathroom.",
    "cand_A": "The bathroom needs cleaning.",
    "cand_B": "One of the bathrooms needs cleaning."
   },
   {
    "item": "part-11",
    "cls": "partitive",
    "ctx": "Control",
    "context": "Our road has dozens of streetlights.",
    "cand_A": "The streetlight is broken.",
    "cand_B": "One of the streetlights is broken."
   },
   {
    "item": "part-13",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The restaurant only had one waiter.",
    "cand_A": "The waiter forgot our order.",
    "cand_B": "One of the waiters forgot our order."
   },
   {
    "item": "part-15",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The band has quite a few singers.",
    "cand_A": "I got a photo with the singer.",
    "cand_B": "I got a photo with one of the singers."
   },
   {
    "item": "dual-02",
    "cls": "duality",
    "ctx": "Support",
    "context": "Tom only has two sisters.",
    "cand_A": "Both of his sisters are teachers.",
    "cand_B": "All of his sisters are teachers."
   },
   {
    "item": "dual-04",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ruth owns a dozen houses.",
    "cand_A": "She rents both of her houses out.",
    "cand_B": "She rents all of her houses out."
   },
   {
    "item": "dual-06",
    "cls": "duality",
    "ctx": "Support",
    "context": "I only bought two plants.",
    "cand_A": "I killed both of them within a week.",
    "cand_B": "I killed all of them within a week."
   },
   {
    "item": "dual-08",
    "cls": "duality",
    "ctx": "Control",
    "context": "Sam has a whole wall of guitars.",
    "cand_A": "He tunes both of his guitars every day.",
    "cand_B": "He tunes all of his guitars every day."
   },
   {
    "item": "dual-10",
    "cls": "duality",
    "ctx": "Support",
    "context": "Leo only has two flatmates.",
    "cand_A": "Both of his flatmates are students.",
    "cand_B": "All of his flatmates are students."
   },
   {
    "item": "dual-12",
    "cls": "duality",
    "ctx": "Control",
    "context": "Ben kept hundreds of chickens.",
    "cand_A": "A fox took both of his chickens.",
    "cand_B": "A fox took all of his chickens."
   },
   {
    "item": "dual-14",
    "cls": "duality",
    "ctx": "Support",
    "context": "Jon only brought two laptops.",
    "cand_A": "Both of the laptops were broken.",
    "cand_B": "All of the laptops were broken."
   },
   {
    "item": "dual-16",
    "cls": "duality",
    "ctx": "Control",
    "context": "My parents invited the whole street.",
    "cand_A": "The neighbours both came.",
    "cand_B": "The neighbours all came."
   },
   {
    "item": "add-01",
    "cls": "additive",
    "ctx": "Support",
    "context": "Lisa saw Dune at the weekend.",
    "cand_A": "Donald saw Dune too.",
    "cand_B": "Donald saw Dune."
   },
   {
    "item": "add-03",
    "cls": "additive",
    "ctx": "Control",
    "context": "Priya failed her driving test.",
    "cand_A": "Marcus passed his driving test too.",
    "cand_B": "Marcus passed his driving test."
   },
   {
    "item": "add-05",
    "cls": "additive",
    "ctx": "Support",
    "context": "Mia ordered the soup.",
    "cand_A": "Josh ordered the soup too.",
    "cand_B": "Josh ordered the soup."
   },
   {
    "item": "add-07",
    "cls": "additive",
    "ctx": "Control",
    "context": "Chloe voted against the proposal.",
    "cand_A": "Dan voted for it too.",
    "cand_B": "Dan voted for it."
   },
   {
    "item": "add-09",
    "cls": "additive",
    "ctx": "Support",
    "context": "I bought a hat in the sale.",
    "cand_A": "My sister bought a hat too.",
    "cand_B": "My sister bought a hat."
   },
   {
    "item": "add-11",
    "cls": "additive",
    "ctx": "Control",
    "context": "My brother never learnt Spanish.",
    "cand_A": "My sister speaks Spanish too.",
    "cand_B": "My sister speaks Spanish."
   },
   {
    "item": "add-13",
    "cls": "additive",
    "ctx": "Support",
    "context": "Tariq failed his driving test.",
    "cand_A": "Holly also failed her driving test.",
    "cand_B": "Holly failed her driving test."
   },
   {
    "item": "add-15",
    "cls": "additive",
    "ctx": "Control",
    "context": "Elif spent Easter at work.",
    "cand_A": "Sam also visited his grandparents.",
    "cand_B": "Sam visited his grandparents."
   },
   {
    "item": "it-02",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Marco climbed the tower last year.",
    "cand_A": "He climbed the tower again this summer.",
    "cand_B": "He climbed the tower this summer."
   },
   {
    "item": "it-04",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Pete cycled ten miles on Saturday.",
    "cand_A": "He ran ten miles again on Sunday.",
    "cand_B": "He ran ten miles on Sunday."
   },
   {
    "item": "it-06",
    "cls": "iterative",
    "ctx": "Support",
    "context": "The bus was late on Monday.",
    "cand_A": "The bus was late again on Tuesday.",
    "cand_B": "The bus was late on Tuesday."
   },
   {
    "item": "it-08",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Rhys lost his wallet on Friday.",
    "cand_A": "He lost his keys again this morning.",
    "cand_B": "He lost his keys this morning."
   },
   {
    "item": "it-10",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Adam burned the toast yesterday.",
    "cand_A": "He burned the toast again this morning.",
    "cand_B": "He burned the toast this morning."
   },
   {
    "item": "it-12",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Joel forgot his lunch last week.",
    "cand_A": "He forgot his password again today.",
    "cand_B": "He forgot his password today."
   },
   {
    "item": "it-14",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Kofi broke a plate on Monday.",
    "cand_A": "He broke a plate again on Wednesday.",
    "cand_B": "He broke a plate on Wednesday."
   },
   {
    "item": "it-16",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Noor rode a camel on holiday.",
    "cand_A": "She rode a horse again at the weekend.",
    "cand_B": "She rode a horse at the weekend."
   },
   {
    "item": "fact-01",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The meeting was cancelled this morning.",
    "cand_A": "Sam knows that it was cancelled.",
    "cand_B": "Sam thinks that it was cancelled."
   },
   {
    "item": "fact-03",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The storm might have passed now.",
    "cand_A": "Ali knows that it has passed.",
    "cand_B": "Ali believes that it has passed."
   },
   {
    "item": "fact-05",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The train was delayed by an hour.",
    "cand_A": "Carl realised that it was delayed.",
    "cand_B": "Carl thought that it was delayed."
   },
   {
    "item": "fact-07",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The bridge might be closed for repairs.",
    "cand_A": "Eli knows that the bridge is closed.",
    "cand_B": "Eli thinks that the bridge is closed."
   },
   {
    "item": "fact-09",
    "cls": "factivity",
    "ctx": "Support",
    "context": "My boss is on holiday this week.",
    "cand_A": "Everyone knows that she's away.",
    "cand_B": "Everyone thinks that she's away."
   },
   {
    "item": "fact-11",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The flight may have been cancelled.",
    "cand_A": "Ivy found out that it was cancelled.",
    "cand_B": "Ivy heard that it was cancelled."
   },
   {
    "item": "fact-13",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The dog has already been fed today.",
    "cand_A": "The kids know that it has been fed.",
    "cand_B": "The kids think that it has been fed."
   },
   {
    "item": "fact-15",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The lift might not be working.",
    "cand_A": "Max realised that the lift wasn't working.",
    "cand_B": "Max thought that the lift wasn't working."
   },
   {
    "item": "cos-02",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Marta used to drive to work.",
    "cand_A": "She stopped driving to work.",
    "cand_B": "She doesn't drive to work."
   },
   {
    "item": "cos-04",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Raj never drank coffee at university.",
    "cand_A": "He gave up coffee.",
    "cand_B": "He doesn't drink coffee."
   },
   {
    "item": "cos-06",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Pia used to go to church every week.",
    "cand_A": "She stopped going to church.",
    "cand_B": "She doesn't go to church."
   },
   {
    "item": "cos-08",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Seb never gambled in his twenties.",
    "cand_A": "He quit gambling.",
    "cand_B": "He doesn't gamble."
   },
   {
    "item": "cos-10",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Will used to take the bus to work.",
    "cand_A": "He quit taking the bus.",
    "cand_B": "He doesn't take the bus."
   },
   {
    "item": "cos-12",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "My brother cooked every night as a student.",
    "cand_A": "He started cooking dinner.",
    "cand_B": "He cooks dinner."
   },
   {
    "item": "cos-14",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Xavi didn't use to play golf.",
    "cand_A": "He took up golf.",
    "cand_B": "He plays golf."
   },
   {
    "item": "cos-16",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Grandpa fished a lot as a boy.",
    "cand_A": "He took up fishing.",
    "cand_B": "He goes fishing."
   }
  ],
  "4": [
   {
    "item": "def-02",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The shelter had lots of dogs.",
    "cand_A": "We adopted the dog last week.",
    "cand_B": "We adopted a dog last week."
   },
   {
    "item": "def-04",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "Our garden only has one tree.",
    "cand_A": "The tree is dying.",
    "cand_B": "A tree is dying."
   },
   {
    "item": "def-06",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The hallway has lots of paintings.",
    "cand_A": "I straightened the painting.",
    "cand_B": "I straightened a painting."
   },
   {
    "item": "def-08",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The fridge only had one pear.",
    "cand_A": "I ate the pear for lunch.",
    "cand_B": "I ate a pear for lunch."
   },
   {
    "item": "def-10",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "Our flat has quite a few radiators.",
    "cand_A": "I turned the radiator up.",
    "cand_B": "I turned a radiator up."
   },
   {
    "item": "def-12",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "The field only had one horse in it.",
    "cand_A": "The horse came over to the fence.",
    "cand_B": "A horse came over to the fence."
   },
   {
    "item": "def-14",
    "cls": "definiteness",
    "ctx": "Control",
    "context": "The shop has several changing rooms.",
    "cand_A": "I waited outside the changing room.",
    "cand_B": "I waited outside a changing room."
   },
   {
    "item": "def-16",
    "cls": "definiteness",
    "ctx": "Support",
    "context": "Our street only has one bakery.",
    "cand_A": "I bought bread from the bakery.",
    "cand_B": "I bought bread from a bakery."
   },
   {
    "item": "part-01",
    "cls": "partitive",
    "ctx": "Control",
    "context": "Our street has quite a few cafés.",
    "cand_A": "We had lunch at the café.",
    "cand_B": "We had lunch at one of the cafés."
   },
   {
    "item": "part-03",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The flat only had one bedroom.",
    "cand_A": "I painted the bedroom blue.",
    "cand_B": "I painted one of the bedrooms blue."
   },
   {
    "item": "part-05",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The museum had lots of guides.",
    "cand_A": "The guide showed us around.",
    "cand_B": "One of the guides showed us around."
   },
   {
    "item": "part-07",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The village only has one pub.",
    "cand_A": "We met in the pub on Friday.",
    "cand_B": "We met in one of the pubs on Friday."
   },
   {
    "item": "part-09",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The house has three separate bathrooms.",
    "cand_A": "The bathroom needs cleaning.",
    "cand_B": "One of the bathrooms needs cleaning."
   },
   {
    "item": "part-11",
    "cls": "partitive",
    "ctx": "Support",
    "context": "Our road only has one streetlight.",
    "cand_A": "The streetlight is broken.",
    "cand_B": "One of the streetlights is broken."
   },
   {
    "item": "part-13",
    "cls": "partitive",
    "ctx": "Control",
    "context": "The restaurant had lots of waiters.",
    "cand_A": "The waiter forgot our order.",
    "cand_B": "One of the waiters forgot our order."
   },
   {
    "item": "part-15",
    "cls": "partitive",
    "ctx": "Support",
    "context": "The band only has one singer.",
    "cand_A": "I got a photo with the singer.",
    "cand_B": "I got a photo with one of the singers."
   },
   {
    "item": "dual-02",
    "cls": "duality",
    "ctx": "Control",
    "context": "Tom has seven sisters.",
    "cand_A": "Both of his sisters are teachers.",
    "cand_B": "All of his sisters are teachers."
   },
   {
    "item": "dual-04",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ruth only owns two houses.",
    "cand_A": "She rents both of her houses out.",
    "cand_B": "She rents all of her houses out."
   },
   {
    "item": "dual-06",
    "cls": "duality",
    "ctx": "Control",
    "context": "I bought loads of plants.",
    "cand_A": "I killed both of them within a week.",
    "cand_B": "I killed all of them within a week."
   },
   {
    "item": "dual-08",
    "cls": "duality",
    "ctx": "Support",
    "context": "Sam only has two guitars.",
    "cand_A": "He tunes both of his guitars every day.",
    "cand_B": "He tunes all of his guitars every day."
   },
   {
    "item": "dual-10",
    "cls": "duality",
    "ctx": "Control",
    "context": "Leo has ten flatmates.",
    "cand_A": "Both of his flatmates are students.",
    "cand_B": "All of his flatmates are students."
   },
   {
    "item": "dual-12",
    "cls": "duality",
    "ctx": "Support",
    "context": "Ben only kept two chickens.",
    "cand_A": "A fox took both of his chickens.",
    "cand_B": "A fox took all of his chickens."
   },
   {
    "item": "dual-14",
    "cls": "duality",
    "ctx": "Control",
    "context": "Jon brought a whole box of laptops.",
    "cand_A": "Both of the laptops were broken.",
    "cand_B": "All of the laptops were broken."
   },
   {
    "item": "dual-16",
    "cls": "duality",
    "ctx": "Support",
    "context": "My parents only invited two neighbours.",
    "cand_A": "The neighbours both came.",
    "cand_B": "The neighbours all came."
   },
   {
    "item": "add-01",
    "cls": "additive",
    "ctx": "Control",
    "context": "Lisa has no interest in Dune.",
    "cand_A": "Donald saw Dune too.",
    "cand_B": "Donald saw Dune."
   },
   {
    "item": "add-03",
    "cls": "additive",
    "ctx": "Support",
    "context": "Priya passed her driving test.",
    "cand_A": "Marcus passed his driving test too.",
    "cand_B": "Marcus passed his driving test."
   },
   {
    "item": "add-05",
    "cls": "additive",
    "ctx": "Control",
    "context": "Mia refused to try the soup.",
    "cand_A": "Josh ordered the soup too.",
    "cand_B": "Josh ordered the soup."
   },
   {
    "item": "add-07",
    "cls": "additive",
    "ctx": "Support",
    "context": "Chloe voted for the proposal.",
    "cand_A": "Dan voted for it too.",
    "cand_B": "Dan voted for it."
   },
   {
    "item": "add-09",
    "cls": "additive",
    "ctx": "Control",
    "context": "I found nothing in the sale.",
    "cand_A": "My sister bought a hat too.",
    "cand_B": "My sister bought a hat."
   },
   {
    "item": "add-11",
    "cls": "additive",
    "ctx": "Support",
    "context": "My brother speaks Spanish.",
    "cand_A": "My sister speaks Spanish too.",
    "cand_B": "My sister speaks Spanish."
   },
   {
    "item": "add-13",
    "cls": "additive",
    "ctx": "Control",
    "context": "Tariq passed his driving test.",
    "cand_A": "Holly also failed her driving test.",
    "cand_B": "Holly failed her driving test."
   },
   {
    "item": "add-15",
    "cls": "additive",
    "ctx": "Support",
    "context": "Elif visited her grandparents at Easter.",
    "cand_A": "Sam also visited his grandparents.",
    "cand_B": "Sam visited his grandparents."
   },
   {
    "item": "it-02",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Marco visited the cathedral last year.",
    "cand_A": "He climbed the tower again this summer.",
    "cand_B": "He climbed the tower this summer."
   },
   {
    "item": "it-04",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Pete ran ten miles on Saturday.",
    "cand_A": "He ran ten miles again on Sunday.",
    "cand_B": "He ran ten miles on Sunday."
   },
   {
    "item": "it-06",
    "cls": "iterative",
    "ctx": "Control",
    "context": "The bus was early on Monday.",
    "cand_A": "The bus was late again on Tuesday.",
    "cand_B": "The bus was late on Tuesday."
   },
   {
    "item": "it-08",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Rhys lost his keys on Friday.",
    "cand_A": "He lost his keys again this morning.",
    "cand_B": "He lost his keys this morning."
   },
   {
    "item": "it-10",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Adam burned the rice yesterday.",
    "cand_A": "He burned the toast again this morning.",
    "cand_B": "He burned the toast this morning."
   },
   {
    "item": "it-12",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Joel forgot his password last week.",
    "cand_A": "He forgot his password again today.",
    "cand_B": "He forgot his password today."
   },
   {
    "item": "it-14",
    "cls": "iterative",
    "ctx": "Control",
    "context": "Kofi broke a glass on Monday.",
    "cand_A": "He broke a plate again on Wednesday.",
    "cand_B": "He broke a plate on Wednesday."
   },
   {
    "item": "it-16",
    "cls": "iterative",
    "ctx": "Support",
    "context": "Noor rode a horse on holiday.",
    "cand_A": "She rode a horse again at the weekend.",
    "cand_B": "She rode a horse at the weekend."
   },
   {
    "item": "fact-01",
    "cls": "factivity",
    "ctx": "Control",
    "context": "I'm not sure the meeting was cancelled.",
    "cand_A": "Sam knows that it was cancelled.",
    "cand_B": "Sam thinks that it was cancelled."
   },
   {
    "item": "fact-03",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The storm has passed at last.",
    "cand_A": "Ali knows that it has passed.",
    "cand_B": "Ali believes that it has passed."
   },
   {
    "item": "fact-05",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The train may have been delayed.",
    "cand_A": "Carl realised that it was delayed.",
    "cand_B": "Carl thought that it was delayed."
   },
   {
    "item": "fact-07",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The bridge is closed for repairs this week.",
    "cand_A": "Eli knows that the bridge is closed.",
    "cand_B": "Eli thinks that the bridge is closed."
   },
   {
    "item": "fact-09",
    "cls": "factivity",
    "ctx": "Control",
    "context": "My boss might be on holiday.",
    "cand_A": "Everyone knows that she's away.",
    "cand_B": "Everyone thinks that she's away."
   },
   {
    "item": "fact-11",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The flight was cancelled last night.",
    "cand_A": "Ivy found out that it was cancelled.",
    "cand_B": "Ivy heard that it was cancelled."
   },
   {
    "item": "fact-13",
    "cls": "factivity",
    "ctx": "Control",
    "context": "The dog may already have been fed.",
    "cand_A": "The kids know that it has been fed.",
    "cand_B": "The kids think that it has been fed."
   },
   {
    "item": "fact-15",
    "cls": "factivity",
    "ctx": "Support",
    "context": "The lift isn't working.",
    "cand_A": "Max realised that the lift wasn't working.",
    "cand_B": "Max thought that the lift wasn't working."
   },
   {
    "item": "cos-02",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Marta never drove in her twenties.",
    "cand_A": "She stopped driving to work.",
    "cand_B": "She doesn't drive to work."
   },
   {
    "item": "cos-04",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Raj used to drink a lot of coffee.",
    "cand_A": "He gave up coffee.",
    "cand_B": "He doesn't drink coffee."
   },
   {
    "item": "cos-06",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Pia never went to church as a teenager.",
    "cand_A": "She stopped going to church.",
    "cand_B": "She doesn't go to church."
   },
   {
    "item": "cos-08",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Seb used to gamble a lot.",
    "cand_A": "He quit gambling.",
    "cand_B": "He doesn't gamble."
   },
   {
    "item": "cos-10",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Will never took the bus as a student.",
    "cand_A": "He quit taking the bus.",
    "cand_B": "He doesn't take the bus."
   },
   {
    "item": "cos-12",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "My brother didn't use to cook for himself.",
    "cand_A": "He started cooking dinner.",
    "cand_B": "He cooks dinner."
   },
   {
    "item": "cos-14",
    "cls": "change-of-state",
    "ctx": "Control",
    "context": "Xavi played golf as a teenager.",
    "cand_A": "He took up golf.",
    "cand_B": "He plays golf."
   },
   {
    "item": "cos-16",
    "cls": "change-of-state",
    "ctx": "Support",
    "context": "Grandpa didn't use to go fishing.",
    "cand_A": "He took up fishing.",
    "cand_B": "He goes fishing."
   }
  ]
 },
 "fillers": [
  {
   "item": "fill-01",
   "cls": "filler",
   "ctx": "fit",
   "context": "It was freezing outside.",
   "cand_A": "Tom put on his coat.",
   "cand_B": "Tom put on his sandals.",
   "filler_key": "A"
  },
  {
   "item": "fill-02",
   "cls": "filler",
   "ctx": "fit",
   "context": "Anna was very thirsty.",
   "cand_A": "She asked for some water.",
   "cand_B": "She asked for some bread.",
   "filler_key": "A"
  },
  {
   "item": "fill-03",
   "cls": "filler",
   "ctx": "fit",
   "context": "Mark forgot his umbrella.",
   "cand_A": "He got wet on the way home.",
   "cand_B": "He got dry on the way home.",
   "filler_key": "A"
  },
  {
   "item": "fill-04",
   "cls": "filler",
   "ctx": "fit",
   "context": "The lecture was very boring.",
   "cand_A": "Several students yawned.",
   "cand_B": "Several students cheered.",
   "filler_key": "A"
  },
  {
   "item": "fill-05",
   "cls": "filler",
   "ctx": "fit",
   "context": "Kate's flight left at dawn.",
   "cand_A": "She got up early.",
   "cand_B": "She got up late.",
   "filler_key": "A"
  },
  {
   "item": "fill-06",
   "cls": "filler",
   "ctx": "fit",
   "context": "The soup was very salty.",
   "cand_A": "Raj added more water.",
   "cand_B": "Raj added more salt.",
   "filler_key": "A"
  },
  {
   "item": "fill-07",
   "cls": "filler",
   "ctx": "fit",
   "context": "The exam was very easy.",
   "cand_A": "Most students passed.",
   "cand_B": "Most students failed.",
   "filler_key": "A"
  },
  {
   "item": "fill-08",
   "cls": "filler",
   "ctx": "fit",
   "context": "The room was very dark.",
   "cand_A": "Jo switched on the light.",
   "cand_B": "Jo switched off the light.",
   "filler_key": "A"
  },
  {
   "item": "fill-09",
   "cls": "filler",
   "ctx": "fit",
   "context": "Luis won the lottery.",
   "cand_A": "He was delighted.",
   "cand_B": "He was furious.",
   "filler_key": "A"
  },
  {
   "item": "fill-10",
   "cls": "filler",
   "ctx": "fit",
   "context": "The baby was exhausted.",
   "cand_A": "He fell asleep quickly.",
   "cand_B": "He woke up quickly.",
   "filler_key": "A"
  },
  {
   "item": "fill-11",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "Everyone walked out of the film.",
   "cand_A": "It was not very good.",
   "cand_B": "It was very good.",
   "filler_key": "A"
  },
  {
   "item": "fill-12",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The hotel cost a fortune.",
   "cand_A": "It was not cheap.",
   "cand_B": "It was cheap.",
   "filler_key": "A"
  },
  {
   "item": "fill-13",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The children yawned through the whole play.",
   "cand_A": "They were not interested.",
   "cand_B": "They were interested.",
   "filler_key": "A"
  },
  {
   "item": "fill-14",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "Nobody finished the curry.",
   "cand_A": "It was not very tasty.",
   "cand_B": "It was very tasty.",
   "filler_key": "A"
  },
  {
   "item": "fill-15",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The exam paper made me panic.",
   "cand_A": "It was not easy.",
   "cand_B": "It was easy.",
   "filler_key": "A"
  },
  {
   "item": "fill-16",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "We had to wear coats on the beach.",
   "cand_A": "The weather was not warm.",
   "cand_B": "The weather was warm.",
   "filler_key": "A"
  },
  {
   "item": "fill-17",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The shop had no customers that day.",
   "cand_A": "It was not busy.",
   "cand_B": "It was busy.",
   "filler_key": "A"
  },
  {
   "item": "fill-18",
   "cls": "filler",
   "ctx": "neg-longer",
   "context": "The printer jammed every five minutes.",
   "cand_A": "It was not reliable.",
   "cand_B": "It was reliable.",
   "filler_key": "A"
  },
  {
   "item": "fill-19",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "We laughed the whole way through.",
   "cand_A": "The show was funny.",
   "cand_B": "The show was not funny.",
   "filler_key": "A"
  },
  {
   "item": "fill-20",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The café was packed at lunchtime.",
   "cand_A": "It was busy.",
   "cand_B": "It was not busy.",
   "filler_key": "A"
  },
  {
   "item": "fill-21",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "My new shoes cost very little.",
   "cand_A": "They were cheap.",
   "cand_B": "They were not cheap.",
   "filler_key": "A"
  },
  {
   "item": "fill-22",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The kids ran straight into the sea.",
   "cand_A": "The water was warm.",
   "cand_B": "The water was not warm.",
   "filler_key": "A"
  },
  {
   "item": "fill-23",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "Everyone got full marks on the quiz.",
   "cand_A": "It was easy.",
   "cand_B": "It was not easy.",
   "filler_key": "A"
  },
  {
   "item": "fill-24",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "Our neighbours helped us move in.",
   "cand_A": "They were very kind.",
   "cand_B": "They were not very kind.",
   "filler_key": "A"
  },
  {
   "item": "fill-25",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "The bus came on time every day.",
   "cand_A": "It was reliable.",
   "cand_B": "It was not reliable.",
   "filler_key": "A"
  },
  {
   "item": "fill-26",
   "cls": "filler",
   "ctx": "neg-shorter",
   "context": "I slept for ten hours in the new bed.",
   "cand_A": "It was comfortable.",
   "cand_B": "It was not comfortable.",
   "filler_key": "A"
  },
  {
   "item": "fill-27",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "My sister rang me last night.",
   "cand_A": "She sounded upset.",
   "cand_B": "He sounded upset.",
   "filler_key": "A"
  },
  {
   "item": "fill-28",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "My grandfather turned ninety.",
   "cand_A": "He had a big party.",
   "cand_B": "She had a big party.",
   "filler_key": "A"
  },
  {
   "item": "fill-29",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "My parents moved to Spain.",
   "cand_A": "They love it there.",
   "cand_B": "He loves it there.",
   "filler_key": "A"
  },
  {
   "item": "fill-30",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "The twins are in my class.",
   "cand_A": "They sit near me.",
   "cand_B": "She sits near me.",
   "filler_key": "A"
  },
  {
   "item": "fill-31",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "My aunt sent me a letter.",
   "cand_A": "She wrote it by hand.",
   "cand_B": "He wrote it by hand.",
   "filler_key": "A"
  },
  {
   "item": "fill-32",
   "cls": "filler",
   "ctx": "pronoun",
   "context": "Our old car broke down.",
   "cand_A": "It needs a new engine.",
   "cand_B": "They need a new engine.",
   "filler_key": "A"
  },
  {
   "item": "fill-33",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Ella looked pale.",
   "cand_A": "Her friend said that she was ill.",
   "cand_B": "Her friend said she was ill.",
   "filler_key": null
  },
  {
   "item": "fill-34",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Dan came home late.",
   "cand_A": "He said that the train was delayed.",
   "cand_B": "He said the train was delayed.",
   "filler_key": null
  },
  {
   "item": "fill-35",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "The fridge was empty.",
   "cand_A": "Maya decided that she would go shopping.",
   "cand_B": "Maya decided she would go shopping.",
   "filler_key": null
  },
  {
   "item": "fill-36",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Leo checked the forecast.",
   "cand_A": "It said that rain was coming.",
   "cand_B": "It said rain was coming.",
   "filler_key": null
  },
  {
   "item": "fill-37",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Sophie opened the letter.",
   "cand_A": "It said that she had got the job.",
   "cand_B": "It said she had got the job.",
   "filler_key": null
  },
  {
   "item": "fill-38",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Jamal looked at the sky.",
   "cand_A": "He guessed that it would rain.",
   "cand_B": "He guessed it would rain.",
   "filler_key": null
  },
  {
   "item": "fill-39",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "The team lost the match.",
   "cand_A": "The coach said that they needed more practice.",
   "cand_B": "The coach said they needed more practice.",
   "filler_key": null
  },
  {
   "item": "fill-40",
   "cls": "filler",
   "ctx": "that-optional",
   "context": "Olivia studied every evening.",
   "cand_A": "She hoped that the exam would be easy.",
   "cand_B": "She hoped the exam would be easy.",
   "filler_key": null
  },
  {
   "item": "fill-41",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Ann was moving house.",
   "cand_A": "Tom helped her to pack the boxes.",
   "cand_B": "Tom helped her pack the boxes.",
   "filler_key": null
  },
  {
   "item": "fill-42",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "The kitchen was a mess.",
   "cand_A": "Sara helped Paul to clean it.",
   "cand_B": "Sara helped Paul clean it.",
   "filler_key": null
  },
  {
   "item": "fill-43",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Grandpa's car broke down.",
   "cand_A": "His neighbour helped him to push it.",
   "cand_B": "His neighbour helped him push it.",
   "filler_key": null
  },
  {
   "item": "fill-44",
   "cls": "filler",
   "ctx": "to-optional",
   "context": "Lily was new at school.",
   "cand_A": "Her teacher helped her to find the library.",
   "cand_B": "Her teacher helped her find the library.",
   "filler_key": null
  },
  {
   "item": "fill-45",
   "cls": "filler",
   "ctx": "particle",
   "context": "Jo's coat was on the floor.",
   "cand_A": "She picked the coat up.",
   "cand_B": "She picked up the coat.",
   "filler_key": null
  },
  {
   "item": "fill-46",
   "cls": "filler",
   "ctx": "particle",
   "context": "The music was very loud.",
   "cand_A": "Rob turned the radio down.",
   "cand_B": "Rob turned down the radio.",
   "filler_key": null
  },
  {
   "item": "fill-47",
   "cls": "filler",
   "ctx": "particle",
   "context": "The form had a mistake.",
   "cand_A": "Kim crossed the mistake out.",
   "cand_B": "Kim crossed out the mistake.",
   "filler_key": null
  },
  {
   "item": "fill-48",
   "cls": "filler",
   "ctx": "particle",
   "context": "Ivan finished his cereal.",
   "cand_A": "He put the bowl away.",
   "cand_B": "He put away the bowl.",
   "filler_key": null
  },
  {
   "item": "fill-49",
   "cls": "filler",
   "ctx": "particle",
   "context": "The meeting clashed with lunch.",
   "cand_A": "Priya called the meeting off.",
   "cand_B": "Priya called off the meeting.",
   "filler_key": null
  },
  {
   "item": "fill-50",
   "cls": "filler",
   "ctx": "particle",
   "context": "Max found an old letter.",
   "cand_A": "He threw the letter away.",
   "cand_B": "He threw away the letter.",
   "filler_key": null
  },
  {
   "item": "fill-51",
   "cls": "filler",
   "ctx": "dative",
   "context": "Mary needed a pen.",
   "cand_A": "Jack gave Mary a pen.",
   "cand_B": "Jack gave a pen to Mary.",
   "filler_key": null
  },
  {
   "item": "fill-52",
   "cls": "filler",
   "ctx": "dative",
   "context": "Grandma loves photos.",
   "cand_A": "Liam sent Grandma a photo.",
   "cand_B": "Liam sent a photo to Grandma.",
   "filler_key": null
  },
  {
   "item": "fill-53",
   "cls": "filler",
   "ctx": "dative",
   "context": "The waiter brought the bill.",
   "cand_A": "Ruth handed the waiter her card.",
   "cand_B": "Ruth handed her card to the waiter.",
   "filler_key": null
  },
  {
   "item": "fill-54",
   "cls": "filler",
   "ctx": "dative",
   "context": "Sam's niece turned five.",
   "cand_A": "Sam bought his niece a kite.",
   "cand_B": "Sam bought a kite for his niece.",
   "filler_key": null
  },
  {
   "item": "fill-55",
   "cls": "filler",
   "ctx": "dative",
   "context": "Noah wrote a long letter.",
   "cand_A": "He sent his cousin the letter.",
   "cand_B": "He sent the letter to his cousin.",
   "filler_key": null
  },
  {
   "item": "fill-56",
   "cls": "filler",
   "ctx": "dative",
   "context": "The teacher had the exam results.",
   "cand_A": "She showed the class the results.",
   "cand_B": "She showed the results to the class.",
   "filler_key": null
  }
 ],
 "attention": [
  {
   "item": "check-1",
   "cls": "check",
   "ctx": "check",
   "context": "Ravi bought a new bicycle.",
   "cand_A": "It is blue.",
   "cand_B": "It is and."
  },
  {
   "item": "check-2",
   "cls": "check",
   "ctx": "check",
   "context": "I need bread from the bakery.",
   "cand_A": "It closes at six.",
   "cand_B": "It closes at purple."
  },
  {
   "item": "check-3",
   "cls": "check",
   "ctx": "check",
   "context": "Nadia was in Rome last week.",
   "cand_A": "She came back on Sunday.",
   "cand_B": "She came back on slowly."
  },
  {
   "item": "check-4",
   "cls": "check",
   "ctx": "check",
   "context": "A cat is lying in our garden.",
   "cand_A": "It looks very sleepy.",
   "cand_B": "It looks very under."
  },
  {
   "item": "check-5",
   "cls": "check",
   "ctx": "check",
   "context": "Theo had maths homework.",
   "cand_A": "He finished it quickly.",
   "cand_B": "He finished it the."
  },
  {
   "item": "check-6",
   "cls": "check",
   "ctx": "check",
   "context": "The train to Leeds leaves at noon.",
   "cand_A": "We need to hurry.",
   "cand_B": "We need to under."
  }
 ],
 "practice": [
  {
   "item": "prac-1",
   "cls": "practice",
   "ctx": "practice",
   "context": "The tiny café only had one table.",
   "cand_A": "We sat at the table for an hour.",
   "cand_B": "We sat at a table for an hour."
  },
  {
   "item": "prac-2",
   "cls": "practice",
   "ctx": "practice",
   "context": "Leo went to the cinema on Friday.",
   "cand_A": "He went to the cinema again on Saturday.",
   "cand_B": "He went to the cinema on Saturday."
  },
  {
   "item": "prac-3",
   "cls": "practice",
   "ctx": "practice",
   "context": "Ellie spilled juice on the table.",
   "cand_A": "She wiped the table down.",
   "cand_B": "She wiped down the table."
  }
 ]
};
if (typeof module !== "undefined") module.exports = { STIMULI };
